### ISSUE TITLE
Missing dependency in Syncplay installation guide: zope.interface

### ISSUE THREAD

**Issue by spartan263** [Syncplay/syncplay#102]
Running 'conda install zope.interface' is necessary for Mac OS X users to run Syncplay.  Without it, the Syncplay configuration window will appear and operate normally but the app will immediately crash after clicking 'Store Configuration and run Syncplay'.

The installation guide should be updated:
 http://syncplay.pl/guide/install/

**Comment by blaenk** [comment]
Perhaps this is the cause of #100? Care to check, @mokrates?

**Comment by spartan263** [comment]
For completeness, I also ran 'conda install twisted'.  Not sure if this is exactly the same as 'pip install twisted'.

**Comment by vladashram** [comment]
@blaenk Doesn't seem likely, as that issue is with Windows 10 and this issue is with Mac OS X.

@spartan263 I didn't need to install zope.interface, although I didn't entirely follow the directions. I re-wrote my own install instructions using just homebrew. What version of Python are you using?

**Comment by blaenk** [comment]
I am well aware that they concern different operating systems, but
considering that they both crash at the same point and that no one else is
crashing on Windows 10, it doesn't hurt to check if it's a dependency issue
as well.

It doesn't seem beyond reason that we would already have the all of
the required dependencies from having worked on developing syncplay, I do
vaguely remember installing something about zope.

Also just because an issue specifies the platform on which they're
experiencing an issue doesn't mean that it's only present on that platform,
just that that's where the user observed the issue, unless they state that
they haven't observed the issue on any of the other platforms.

**Comment by vladashram** [comment]
Digging into this, zope.interface should be installed automatically as a part of twisted, which is mentioned in the guide.

**Comment by Et0h** [comment]
In relation to twisted and OS X, someone recently e-mailed me to say that people may need to run `pip install --upgrade pip` to prevent Syncplay from crashing and to note that the wording about qt should be updated to reflect the fact that qt 4.8.7 is out now and so people should be told just to have the latest version of qt rather than to specifically have 4.8.5 (the important thing is that people are not using qt 4.7.4 which causes a crash).

I'll get around to updating the OS X guide the best I can when I have time (probably next month), but finding the precise way to phrase things is quite time-consuming for me as I don't use OS X so am a bit out of my depth with it all.

**Comment by vladashram** [comment]
@Et0h I'll help you out. Conda isn't needed if you use homebrew and pip, which can be used to install everything.

**Comment by alby128** [comment]
Since the instructions have been updated recently, and since a few users have already tested them successfully, I think this issue is closed. Please reopen it if you still have troubles in running Syncplay on macOS.
