### ISSUE TITLE
Doesn't work since VLC 3.0

### ISSUE THREAD

**Issue by phadeb** [Syncplay/syncplay#141]
It looks like the issue with the timing is that VLC has moved from decimal seconds to microseconds.

As a result, it cannot connect to VLC anymore even with the latest lua file
 
![image](https://user-images.githubusercontent.com/8358491/29841515-f3c0eaa8-8d05-11e7-86ba-dcc0b88f3015.png)

**Comment by Et0h** [comment]
That issue was resolved a while back. I just tried with the latest nightly of VLC 3 and the latest build of Syncplay 1.4.0 and the latest version of syncplay.lua (0.3.3) and it worked for me. That said, at present mpv has the best compatibility with some of Syncplay's more advanced functionality (shared playlists and playing streams).
