### ISSUE TITLE
Unable to pause; others auto-unpause immediately

### ISSUE THREAD

**Issue by blue-lightning** [Syncplay/syncplay#155]
Happened recently after my friend reinstalled his Syncplay. Whenever I pause my Syncplay would switch to Not Ready, but then his Syncplay unpauses right away. He has no problem pausing. This happens on both version 1.4 and 1.5 RC1.

**Comment by alby128** [comment]
Can you please tell us which operative system you and your friend use? Also, did you experience this issue on syncplay's official servers or on your private servers? Thanks.

**Comment by Et0h** [comment]
Are you both on 1.5? What players are you both using and version of those
players? If mpc-hc is it a vanilla set up or using MadVR?  What is the file
format of the video? What is your unpause setting?

**Comment by blue-lightning** [comment]
We're on Windows 10. As for the server, it's syncplay.pl:8999. As I've said before, it happened when we're on version 1.4; moved to 1.5 RC yesterday but the problem persists.
My MPC is vanilla, the files are all .MKV. Unpause setting is on default, my friend left it at "Unpause if already set as ready" a while ago but I already told him to switch back. Didn't help.
Here's my full settings below (some entries are removed for privacy's sake):
```
[client_settings]
playerpath = c:\program files\mpc-hc\mpc-hc64.exe
perplayerarguments = {}
slowdownthreshold = 1.5
rewindthreshold = 4.0
fastforwardthreshold = 5.0
slowondesync = False
rewindondesync = True
fastforwardondesync = True
dontslowdownwithme = False
forceguiprompt = True
filenameprivacymode = SendRaw
filesizeprivacymode = SendRaw
unpauseaction = IfOthersReady
pauseonleave = False
readyatstart = True
autoplayminusers = -1.0
autoplayinitialstate = None
sharedplaylistenabled = True
loopatendofplaylist = False
loopsinglefiles = False
onlyswitchtotrusteddomains = True
trusteddomains = [u'youtube.com', u'youtu.be']
publicservers = [u'syncplay.pl:8995', u'syncplay.pl:8996', u'syncplay.pl:8997', u'syncplay.pl:8998', u'syncplay.pl:8999']

[gui]
showosd = True
showosdwarnings = True
showslowdownosd = True
showdifferentroomosd = False
showsameroomosd = True
shownoncontrollerosd = False
showdurationnotification = True

[general]
language = 
checkforupdatesautomatically = True
lastcheckedforupdates = 2017-10-23 15:13:55.630000

[server_data]
host = syncplay.pl
port = 8999
password = None
```

And my friend's:
```
[general]
language = en
checkforupdatesautomatically = True
lastcheckedforupdates = 2017-10-23 15:18:01.577000

[client_settings]
playerpath = c:\program files\mpc-hc\mpc-hc64.exe
perplayerarguments = {}
slowdownthreshold = 1.5
rewindthreshold = 4.0
fastforwardthreshold = 5.0
slowondesync = True
rewindondesync = True
fastforwardondesync = True
dontslowdownwithme = False
forceguiprompt = True
filenameprivacymode = SendRaw
filesizeprivacymode = SendRaw
unpauseaction = IfOthersReady
pauseonleave = True
readyatstart = True
autoplayminusers = -1.0
autoplayinitialstate = None
mediasearchdirectories = {}
sharedplaylistenabled = True
loopatendofplaylist = False
loopsinglefiles = False
onlyswitchtotrusteddomains = True
trusteddomains = [u'youtube.com', u'youtu.be']
publicservers = [u'syncplay.pl:8995', u'syncplay.pl:8996', u'syncplay.pl:8997', u'syncplay.pl:8998', u'syncplay.pl:8999']

[gui]
showosd = True
showosdwarnings = True
showslowdownosd = True
showdifferentroomosd = False
showsameroomosd = True
shownoncontrollerosd = False
showdurationnotification = True

[server_data]
host = syncplay.pl
port = 8999
password = 
```

**Comment by Et0h** [comment]
Expected behaviour: If you press pause while unpaused it will pause and set you to not ready. It will also pause for others.

Question? What versions of MPC-HC are you both oon?

Some things to try:
1) Backing up both of your configs by exporting them then resetting MPC-HC to the defaults
2) Pressing pause in Syncplay window rather than MPC-HC. (Window -> Show Playback Buttons in menu bar)
3) Updating your graphics drivers
4) Trying it in both full-screen and windowed mode and seeing if that makes a difference.

**Comment by Et0h** [comment]
5. Both update to the latest version of MPC-HC.

**Comment by ShiroNek0** [comment]
I'm friend of blue-lightning. Last night we tested all ideas you suggest + bunch of ideas we could think of. Finally traced down the problem.

We both use MPC-HC ver v1.7.13 (latest stable version).

Result of testing
1. No Good
2. No Good
3. No Good. We both updated to latest NVIDIA driver
4. No Good
5. No Good

After that, I thought we needed to narrow down the scope: Does problem lie in only MPC-HC? Or Syncplay? Or both? 

Logically thinking,  problem comes from my side. Because I can pause but blue-lightning cant, my Syncplay unpauses every time he hits Pause button.

6. We switched to MPV. The problem disappears.
Same with combo MPC (blue-lightning)  and MPV (me).
But problem persists on MPV/MPC (blue-lightning) and MPC (me)
=> Problem lies in my side MPC.

7. Reinstall my side MPC. No good.

8. I began testing all components I used with MPC (LAV Video/Audio Decoder, xySubFilter, madVR).

Surprisingly, problem lies in madVR.
Problem disappears when I switch Output option from "madVR" to "Enhanced Video Renderer (custom presenter)".
Tested with madVR 0.92.6 and 0.92.7 (recent versions within 3 weeks)

**Conclusion:** My guess is recent madVR versions break the workflow of MPC+Syncplay.

**Comment by Et0h** [comment]
Thanks for working to resolve this. http://syncplay.pl/guide/trouble/ already lists one known issue with madVR, which is "If you are have set the video filter to madVR then you will need to revert to the default filter or disable the ‘delay playback start until render queue is full’ option within madVR." - that's why I asked earlier if people were using vanilla MPC-HC or madVR. Does unchecking the 'delay playback' option in madVR fix the problem?

**Comment by blue-lightning** [comment]
Disable "delay playback" solve the issue. Sorry for not reading the troubleshooting guide before bringing this up.
