### ISSUE TITLE
System messages indistinguishable from messages sent by user

### ISSUE THREAD

**Issue by 730730** [Syncplay/syncplay#175]
When there's a message like "\<Bob\> left the room." it looks exactly the same as "\<Bob\> hey what's up", it would be nice if system messages were colored differently or something like that, like in IRC.

**Comment by Et0h** [comment]
In Syncplay 1.5.2 Syncplay no longer says "\<bob\> left the room", it says "bob left the room" so you know that if it has the <> and the blue highlighting it is because it is from a chat messaging.

In mpv there is also a system introduced as part of the move to in-player messages: chat messages are in white, notifications are in cyan, and alerts are colour-coded depending on if the news is good (green), concerning (red) or neutral (grey).

In the future there could be custom colour-coding for messages or other formatting changes for within the Syncplay window. If people who have checked out the current 1.5.2 system have strong views about whether they want this additional feature, or what the defaults should be, then please let me know.

**Comment by xNinjaKittyx** [comment]
I haven't paid much attention to the chat recently, but wouldn't something like this help distinguish?

*Bob entered the room.*
**\<Bob\>**: Hey guys what's up
**\<EcksDee\>**: Nothing much, let's watch...
**\<Bob\>**: Nah I gotta head out
*Bob left the room.*
**\<EcksDee\>**: ...

Italicizing system messages, and Bolding names when it's a chat message. 

Of course, ideally, having a custom color-coding would be amazing.

**Comment by Et0h** [comment]
@xNinjaKittyx If you are talking about the notification window it already emboldens the text.

Some questions about how you think the notification window messages should work:
1. Did you want all messages other than chat messages to be italicised?
2. How would you think custom colour-coding would work?
3. Having a colon after <> is not the mIRC convention - is it the convention from somewhere else?

**Comment by xNinjaKittyx** [comment]
Ok, I took a look at the client again.

So yeah, you're right. it already boldens the users when they're using USER messages.

I think the style that you have listed here should be fine. Italicizing all system messages *should* be okay. However, I don't think ERROR messages should be italicized, since they should already be obvious by their bright red color.

I would have no idea how color coding would work. Right now it seems like the only 4 things that would be "customizable" would be USER_MESSAGE, USERNAME, NOTIFICATION_MESSAGE, and ERRORNOTIFICATION. I wouldn't know.

I only added the colon because I didn't know what the default for syncplay was. I don't think it's a problem to have no colon.

However, right now Syncplay has a 1 space gap between User and Message. Chats like Discord (compact) and Youtube use a 2 space gap, which seems to make it easier to read (imo) but that's totally up to you.

**Comment by Et0h** [comment]
I tried out the example Ig ave earlier and sometimes it was nearly an entire screen of text in italics which did not look good on my screen. I will try out a 2 space gap and various other things to find some new defaults I like. Further suggestions welcome :)

**Comment by Et0h** [comment]
Issue closed because the reported problem of join/leave messages being indistinguishable from chat messages was resolved in f5c6b8f when <> was removed from user join/leave messages. More style customisation options" is listed as an idea at https://syncplay.pl/about/ideas/
