### ISSUE TITLE
Feature request: Implement syncplay-web-client and integrate video.js

### ISSUE THREAD

**Issue by fracting** [Syncplay/syncplay#183]
For people who like to run own syncplay-server, it would be nice to also run an HTTP server on the same machine, hosting the video file with HTTP access, and provide a web version of syncplay-client, which talks to an embedded html5 video player like video.js [1]

In this case, a group of users who want to use syncplay does not have to install any application on local machine, a web browser is enough.

How do you like the idea?

[1] https://github.com/videojs/video.js

**Comment by Et0h** [comment]
Thanks for your suggestion. I can see why this may be convenient, but I want to focus on what only Syncplay does rather than expand into other areas such as being a file sharing service or a browser-based sync service. I fear the dangers of 'mission creep' and the security (and possibly legal) implications of going into fields where I have no experience.

Dedicated web server software already exits, e.g. Apache and nginx, and there is an unofficial third-party implementation of Syncplay for HTML available from https://github.com/mo3rfan/syncplay-web that people can volunteer to progress further.

**Comment by fracting** [comment]
Hi @Et0h, thanks for the quick response, syncplay-web is helpful, thanks! I understand your points, totally make sense, closing the issue. Thanks for the great project :)
