### ISSUE TITLE
PotPlayer support?

### ISSUE THREAD

**Issue by sarim** [Syncplay/syncplay#218]

**Comment by Et0h** [comment]
Thank you for the suggestion, but last we checked PotPlayer lacked the APIs that Syncplay needs to synchronise playback. In any case, maintaining support for mpv, VLC, MPC-HC and MPC-BE is already quite a commitment for our current developers.

We recommend mpv for the best Syncplay experience and expect that due to its advanced scripting support our mpv experience will continue to improve in a manner not possible with other players. If there is a feature that you like in a player which you do not see in mpv then we suggest that you become an mpv developer so that you can add that feature to mpv.

**Comment by SoNickRND** [comment]
![image](https://github.com/Syncplay/syncplay/assets/125238/43e60e60-2cb5-4df5-97c0-99bd7c29484b)
