### ISSUE TITLE
Latest Pyside2 update seems to break GUI support on Arch Linux

### ISSUE THREAD

**Issue by alxpettit** [Syncplay/syncplay#221]
This is an issue several people reported [here](https://aur.archlinux.org/packages/syncplay/). I have confirmed it personally.

Unfortunately I don't know enough about Pyside2 to have a patch for this one, but it looks like something in the layout of the modules has changed between `pyside2-5.12.0-1` and `pyside2-5.12.1-1`. On the latter version, Syncplay simply outputs `Could not import GUI libraries. If you do not have PySide installed then you will need to install it for the GUI to work.`

Unfortunately, it looks like your `try... except` statements in `ConfigurationGetter` eat all raised exception details even when passing `--debug`... you might want to fix that if it's convenient! :P

I removed the intelligent import handling code, and here's the exception that's apparently being raised:

```
  File "/usr/bin/syncplay", line 21, in <module>
    SyncplayClientManager().run()
  File "/usr/lib/syncplay/syncplay/clientManager.py", line 9, in run
    config = ConfigurationGetter().getConfiguration()
  File "/usr/lib/syncplay/syncplay/ui/ConfigurationGetter.py", line 487, in getConfiguration
    from syncplay.vendor.Qt import QtWidgets, IsPySide, IsPySide2
ImportError: cannot import name 'QtWidgets' from 'syncplay.vendor.Qt' (/usr/lib/syncplay/syncplay/vendor/Qt.py)
```

**Comment by albertosottile** [comment]
The reason why the `try... except` does not provide the exception details is that those details are not that useful, as you can see, because `Qt.py` (the shim we use to support `PySide1` and `PySide2` at the same time) also masks the true error message. 

In any case, we recently fixed an issue with `pyside2 5.12.1` here (https://github.com/Syncplay/syncplay/commit/89f8a28f3f76d5ce864556bbe3244ee6a1577d01) but I do not think the error you are seeing is related to that. 

I would say that there is an issue with the `pyside2-5.12.1-1` package in AUR, most likely a mismatch between the `pyside2` and `shiboken2` versions. Could you please run `python -c "from PySide2.QtCore import __version__; print(__version__)"` and paste here its output?

**Comment by alxpettit** [comment]
Oh, yeah, I forgot about the shim! Would it be feasible to add debug-mode features to `Qt.py` or is that strictly an upstream issue?

On a side note, it should be noted that AUR is not the official Arch Linux repos -- it uses the same resources of the official Arch Linux repos, but is maintained by the community and often the packages are build client-side. The closest thing I could analogize it to is Ubuntu's PPA system, but it's a bit different from that. Anyway, that doesn't have much to do with this, but I wanted to point out `pyside2-5.12.1-1` was an official package distributed in the Arch Linux repos -- it's not from AUR. Errors in official packages are pretty rare, but they do happen sometimes.

And you're right, there may be something wrong with the package that was built. Unfortunately, I got something rather strange when I tried to import `PySide2.QtCore`:
`ImportError: /usr/lib/python3.7/site-packages/PySide2/QtCore.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN8Shiboken10ObjectType22hasSpecialCastFunctionEP13SbkObjectType`

It should be noted that many people are claiming the `syncplay-git` package is working for them. The way that package works is it automatically clones from the git repo and builds from that, updating the version number dynamically. So that's one thing that points in the direction of this regression maybe already being solved somehow in the git branch.

I'll go ahead and confirm that for myself and do a little more digging. I'll let you know what I find!

**Comment by albertosottile** [comment]
The `ImportError` you pasted points me in the direction of a version mismatch between `pyside2` and `shiboken2`. Unfortunately, these packages are not yet independent from each other, so they must be updated at the same time (see one of the issues about this topic on the Qt for Python tracker, e.g. this one https://bugreports.qt.io/browse/PYSIDE-935).

I'd advise the AUR or Arch Linux maintainers to check if they are respecting this fundamental condition and distributing these two packages together. 

In the meantime, I am going to close this issue, since it does not appear to be related to Syncplay.

**Comment by alxpettit** [comment]
Yeah, I suspected as much. I actually was doing a full system update to check if something was out of date -- and lo and behold, the GUI works now in Syncplay 1.6.3. Still not sure what the regression was in 1.6.1 and 1.6.2 or even if there was a regression in your codebase or somewhere else. I'll post here if I have any more updates!
