### ISSUE TITLE
Feature request: Queue videos (and more controls?) without graphical interface

### ISSUE THREAD

**Issue by Slider-Whistle** [Syncplay/syncplay#262]
I imagine this would work through a command called "q" or "queue". Could assume local file if URI is "file:" or none, passed to media player as-is if it's HTTP or FTP or whatever.
I can't see much else crucial functionality that's missing without the GUI, but I guess it might be a good goal to make anything possible through the chat interface.

**Comment by Et0h** [comment]
Are you talking about adding files to the playlist through the console interface? What is the use case for this?

**Comment by Slider-Whistle** [comment]
Maybe through the console interface if the user has an active terminal, but I mean mostly through the chat itself. I just think that people would find it more convenient.

**Comment by Et0h** [comment]
Is your idea that queue would add a filename/URL to the bottom of the playlist? That could make it slightly quicker to add YouTube videos, etc, to the playlist.

**Comment by Slider-Whistle** [comment]
Yeah, as long as the user has permissions. I don't think such a command exists in Cytube or similar services, but it's common enough with chatbots and stuff that I feel like I've gotten used to it.

**Comment by FichteFoll** [comment]
Related to #272 and #232, where I want to add videos to the playlist from the clipboard and from an external program through CLI respectively.

If a command interface was implemented for the chat and that would also be available from the CLI to execute one-off commands, that would be sweet.

One thing to consider would be adding multiple URLs or files, separated by a newline. The chat is inherently based on single line messages and not suited for adding multiple URLs, unless it became multi-line aware, supporting auto-resizing and a shift+enter binding to insert a newline instead of sending the message, for example.

**Comment by TWINGSISTER** [comment]
Thanks for this software, it is great!
This could be of unvaluable interest in classrooms.
Whenever you have a ICT labo with some PC with loudspeakers and want to show a video you need student to use headphones or there will be a noisy mess.
Synching all the PC will solve the problem and help the teacher to stop playing to add some comment.

It would be nice if the server can expose an http API with three or four basic commands like
-Play this URL starting at this time (may be either video| mp3 audio )
-Stop/Fade out Playing now|at time
-Resume Playing
-Set volume to...

Then this, imho, will be the right start to a very big deal!

If you can provide Python code for this i think I can translate this in PHP and make this a Wordpress plugin and
you will have the support for internet radio with unlimited possibilities and no copyright infringment. Wordpress will just store and broadcast some (possibly hashed) youtu.be URLs  (that is something that a lot of WP plugins are already doing with no encryption) 
Client will download the music, if they can do that then it is up to Youtu.be to pay for the royalties.
Nowadays streaming a mix with Icecast is a copyright infringment. This will change the scenario fora totally free  Internet Radio.

 Google for Radionomy and see. They failed and left many amateur broadcaster  with no option. So this could be the right moment for this.

**Comment by Et0h** [comment]
@TWINGSISTER What you are asking for falls outside of this issue. If you want web access to Syncplay and other features then please create a separate issue to request those features and then they can be discussed.

**Comment by Et0h** [comment]
@TWINGSISTER While it is great if you can make use of Syncplay to support education, our primary use case is to support faraway friends watch stuff together over the Internet.

We don't want to add too many features above and beyond this because it adds complexity to the code (which makes it harder to maintain), adds complexity to the UI (which makes it harder for users to use the software), and takes up our limited development time.

That said, Syncplay is open source so anyone is free to fork the code and add whatever features they link to suit their specific use case. If you or anyone else in the education community volunteered to create a 'Syncplay for Schools' fork in Python then I would be happy to provide advice and guidance.

> This could be of unvaluable interest in classrooms.
> Whenever you have a ICT labo with some PC with loudspeakers and want to show a video you need student to use headphones or there will be a noisy mess.
> Synching all the PC will solve the problem and help the teacher to stop playing to add some comment.

Syncplay is not designed for on-site syncing, so we do not guarantee the level of accuracy needed to ensure that everyone sees everything  at the same millisecond. However, if that works for you then great.

> 
> It would be nice if the server can expose an http API with three or four basic commands like
> -Play this URL starting at this time (may be either video| mp3 audio )
> -Stop/Fade out Playing now|at time
> -Resume Playing
> -Set volume to...
> 
> Then this, imho, will be the right start to a very big deal!

Why does this need to be a HTTP API?

We don't currently support volume control in Syncplay, and have no plans to add such a feature as it is not needed for our core use case.

**Comment by FichteFoll** [comment]
Has this been added? I don't see a relevant commit in the history.

**Comment by Et0h** [comment]
Yes, adding files to the playlist via the console was added via PR #327
