### ISSUE TITLE
Dark theme for not hurting our eyes at movie nights

### ISSUE THREAD

**Issue by sxiii** [Syncplay/syncplay#273]
This topic would be extremely important for me. When I switch from the black movie background to chat sometimes or configuration; white background kicking eyes off. Would be nice to have a globally "dark mode".

**Comment by Et0h** [comment]
At present Syncplay mostly uses the PySidedefault colours which basically uses the style that Windows tells it to use, so for example if you enable a high contrast display with white-on-black then that is what Syncplay will use.

If someone wanted to add a --dark-mode command line option and to set it to use a different colour scheme then I would be happy for them to make the PR for this.

**Comment by sxiii** [comment]
@Et0h never used SyncPlay on Windows, only on Manjaro and Ubuntu. :dagger: 

--dark-mode would be really nice.

**Comment by Et0h** [comment]
@sxiii Ah, you're right. I use Syncplay on Windows so that's what I thought of first. By Windows I should have said 'the OS' (or is it 'the desktop environment'?).

**Comment by sxiii** [comment]
@Et0h right! =)) Maybe I would try adding a dark mode set if you can lead me through places that are used in PySide / the toolkit used for develop the app? Thanks

**Comment by CalMaciborka** [comment]
Just gonna say a dark mode on Windows would be very nice. Very jealous of the MacOS dark mode.

**Comment by sxiii** [comment]
Maybe we should start picking up tips so we can give some BATs or other crypto to actual developer who will make a --dark-mode for Syncplay. :)

**Comment by daniel-123** [comment]
@sxiii: I took a look at it since Syncplay never used anything specific in terms of theming. Because it's using Qt, it also uses whatever theme Qt has set for it. This means on Qt based desktop environments it will use the system theme.

If you aren't using Qt based desktop environment you can try using [qt5ct](https://sourceforge.net/projects/qt5ct/) which I just confirmed that works. Or any of the other methods outlined [here on Arch Wiki](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications).

It probably wouldn't be particularly hard to code Syncplay specific theme dialog, but I'm not entirely sure if it's worthwhile given that standard tools already provide that functionality.

**Comment by sxiii** [comment]
Oh great @daniel-123 . Thank you very much for pointing out. I'll check the qt5ct for sure! Maybe at least it worth mentioning on how to change the theme for both cases (using Qt and not using Qt env).

**Comment by CalMaciborka** [comment]
I'd actually pay good money for a dark mode on Windows. There are definitely many people I know that would love it.

**Comment by sxiii** [comment]
> I'd actually pay good money for a dark mode on Windows. There are definitely many people I know that would love it.

You can do two things: first, try to compile qt5ct on windows and see if it works (I know it should be possible to integrate due to KDE having some windows versions) or maybe there is another qt theme control panel for windows out there. Second, you might just ditch windows or install any lightweight linux just for the watching movies together or even cook a live USB flash for this goal and have a dark theme with this qt5ct. It should be even pretty easy to even write own theme now. Or just use the default ones/find ready on the theme-ing websites. :)

**Comment by sxiii** [comment]
@CalMaciborka have you managed to run dark theme in windows finally? :)
