### ISSUE TITLE
Double-clicking file in shared playlist doesn't reset timer.

### ISSUE THREAD

**Issue by CalMaciborka** [Syncplay/syncplay#280]
Maybe this is only an issue for MPC but when clicking the next file in the shared playlist the time on the video carries over and must be manually set to 00:00. This leads to a lot of half second spoilers.

**Comment by Et0h** [comment]
Someone started working on a fix at https://github.com/Syncplay/syncplay/pull/239 but work on it stalled. Until it is fixed a workaround is to all use mpv which does reset playback when you change selection: https://mpv.io/

**Comment by soredake** [comment]
Any progress on this?

**Comment by Et0h** [comment]
I am not aware of anyone having made any progress on this, so if you want to address the issues I highlighted with #239 then please do so.

**Comment by Et0h** [comment]
This issue is hopefully resolved by 7d1fda5 which is available as part of https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.5#files - please test it and let me know.

**Comment by TeamDman** [comment]
Seems to still be happening when we tried v1.6.5
https://streamable.com/qhhehc

**Comment by soredake** [comment]
Yes, 1.6.5 does not resets.

**Comment by Et0h** [comment]
Thanks for the feedback. I've now done more work on how Syncplay handles syncing on join and playlist change to hopefully resolve this issue.

Please try out https://bintray.com/syncplay/Syncplay/Syncplay/v1.6.5#files again to see the changes in f8b8032ef6e84e808e9ff861ad50846fbd97c237 and let me know if it fixes the issue and if it creates any new issues.

Things you can test include:
1. Joining empty room with no file, with room part way through playing file while file is PLAYING
2. Joining empty room with no file, with room part way through playing file which is PAUSED
3. Joining room with incorrect file, with room part way through playing file while file is PLAYING
4. Joining room with incorrect file, with room part way through playing file which is PAUSED
5. Joining room with correct file, with room part way through playing file while file is PLAYING
6. Joining room with correct file, with room part way through playing file which is PAUSED
7. File change due to changing playlist selection while file is PLAYING
8. File change due to changing playlist selection while file is PAUSED
9. File change due to deleting the currently playing file from the playlist
10. Auto-play enabled and advancing file

**Comment by TeamDman** [comment]
_Seems_ to be working now!
I'll make sure to post back if it does somehow start happening again.

Thanks!
