### ISSUE TITLE
Chat font settings don't stick

### ISSUE THREAD

**Issue by SingerCo** [Syncplay/syncplay#281]
When adjusting chat message input and output font size or font on Mac OS Catalina, any changes vanish immediately upon closing the window. As a minor additional piece, all settings in the font menu are in German.

![Recording of issue](https://user-images.githubusercontent.com/61002377/77679541-47c32d00-6f58-11ea-816f-b981de4a8405.gif)

**Comment by Et0h** [comment]
Just checked and changing font size doesn't seem to work in Windows either. You should be able to probably change the values manually by opening syncplay.ini or .syncplay file and modifying the value for chatInputRelativeFontSize and chatOutputRelativeFontSize.

The German issue should be fixed in Syncplay 1.6.5. The change is: 5aee6d9#diff-f2f4408f1aa0211e78de0c32bf8765dc. That version isn't out yet, though.
