### ISSUE TITLE
syncplay tracebacks upon execution

### ISSUE THREAD

**Issue by Mikaela** [Syncplay/syncplay#283]
```
Traceback (most recent call last):
  File "/home/mikaela/.local/bin/syncplay", line 14, in <module>
    from syncplay import ep_client
  File "/home/mikaela/src/github.com/syncplay/syncplay/syncplay/ep_client.py", line 3, in <module>
    from syncplay.clientManager import SyncplayClientManager
  File "/home/mikaela/src/github.com/syncplay/syncplay/syncplay/clientManager.py", line 2, in <module>
    from syncplay import ui
  File "/home/mikaela/src/github.com/syncplay/syncplay/syncplay/ui/__init__.py", line 9, in <module>
    from syncplay.ui.gui import MainWindow as GraphicalUI
  File "/home/mikaela/src/github.com/syncplay/syncplay/syncplay/ui/gui.py", line 127, in <module>
    class AboutDialog(QtWidgets.QDialog):
TypeError: 'Shiboken.ObjectType' object is not iterable
```

I am getting this on Debian GNU/Linux bullseye/sid and my friend on Ubuntu 19.10 is getting:

```
 % ./syncplayClient.py 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

zsh: abort (core dumped)  ./syncplayClient.py
```

**Comment by daniel-123** [comment]
It seems that this is a bug on [intersection between Python 3.8 and PySide](https://bugreports.qt.io/browse/PYSIDE-939). I also saw it on my Debian Testing system. As a workaround it's possible to either:

- Use older Python 3.7
- Upgrade to PySide 5.14 where the issue is fixed (it's in Debian Experimental branch).

In [source of PySide 5.13.2](https://code.qt.io/cgit/pyside/pyside-setup.git/tree/build_scripts/config.py?h=5.13.2) there is explicit lack of Python 3.8 as supported version.

Since this is all an upstream issue, I don't think Syncplay can do much about it. Except maybe providing a clear message about using incompatible versions of libraries. Still it's kinda weird how those two versions happily exist in Debian Testing and Sid repos. Do you want to submit a bug to Debian package team? I can do that if you aren't up to it.
