### ISSUE TITLE
Some thoughts on UI/UX

### ISSUE THREAD

**Issue by AtilioA** [Syncplay/syncplay#293]
During my couple of years of using Syncplay I've noticed a few things that could be changed:

- Save path to media of previous Syncplay instance
    From time to time I end up having to start Syncplay again, whether it is because I forgot to change some setting or because of some bug. Syncplay already remembers the media player path (not to mention username and room), so why not save the path to the video? It wouldn't bother someone who always changes the path/URL and could make the experience smoother to everyone else.

- '_Path to video (optional)_' label: remove '(optional)' and mention URL support
    The optional might mislead new users as it did to me. Yes, you can change media afterwards so technically it isn't a mandatory argument but you could say the same for the room. The label could also mention streaming support briefly (as in 'Path to video or URL').

- Rearrange some options under 'messages' tab in settings
    'Warn about media duration mismatches' is an OSD warning, so why put it in another section? My suggestion:
    ![2020-04-12 10_11_46-Syncplay configuration](https://user-images.githubusercontent.com/27153776/79069627-0e9ff200-7ca6-11ea-9a50-4d577236d55d.png)

- Add "Save" button?
    A "save"-only button should be considered since the only way to save changes made to Syncplay is saving the settings and starting it right away. We already have 4 buttons so it might bloat the interface.

**Comment by daniel-123** [comment]
My 2 cents about those points:
> Save path to media of previous Syncplay instance
Well, this would seem really weird to me at least. For one thing it's exceedingly rare for me to open the same file more than once. Another thing is that I almost never go through the settings window and instead start Syncplay from "open with" menu of a specific file. Running it from the shortcut/menu is something I use for rare cases where I actually want to start it without any file or change a setting.
The option to never show the setting dialog upon startup was included thinking it would be useful for people starting it directly from shortcut. So they won't need to see the settings window each time.
I would really like some extra comments how others feel about this behavior.
>'Path to video (optional)' label: remove '(optional)' and mention URL support
Supporting URLs is media player dependent and it always is slightly wonky, at least in my experience.
Path to the file is most definitely optional (I never use it). That said I could see how omitting it in favor of somehow marking mandatory fields (by red outline for example?) could improve user experience. Yet again - I very rarely use the settings dialog in first place so I would welcome other comments.
>Rearrange some options under 'messages' tab in settings
I think this has gotten somewhat messy because those warnings are much older than OSD support. And OSD support is player dependent - I know it works in mpv and I think it also works in VLC. I'm not sure if it works also in MPC-HC.
At very least this could use a revisit, but it requires input about how each player works with OSD exactly.
>Add "Save" button?
What exactly should that button do? Just write settings to the file and let you then click another button to run it?
I don't really see need for it. In the odd case where you just want to modify the settings you have you can simply close the window afterwards.

**Comment by AtilioA** [comment]
Thanks for your feedback!
Cool, I've never opened Syncplay from the context menu. As I said it is common for me and friends to open the same file more than once, don't know about others though.
Also I forgot about the whole thing about player compatibility, thanks for noting that.

**Comment by Et0h** [comment]
Most of the points have been covered, but a few additional things to note:

>Rearrange some options under 'messages' tab in settings

All of the options under "Enable OSD Messages" are disabled if you  uncheck "Enable OSD Messages". If I recall correctly the "Warn about media duration mismatches" option is relevant even if OSD messages are disabled because it changes whether or not the auto-play/auto-advance feature is enabled (as it usually only works if there are no mismatches). This is my reading of the description of "Play when all ready / Min users" in https://syncplay.pl/guide/client/ and my recollection, but isn't explicitly mentioned anywhere because the "Warn about media duration mismatches" pre-dates the readiness feature.

> Path to video (optional)

I use Syncplay with shared playlists, so very rarely specify a video path.

>'Path to video (optional)' label: remove '(optional)' and mention URL support

In the tooltip description it does mention that it also works for streams and it gives even more detail in the user guide at https://syncplay.pl/guide/client/ which notes that streams only currently work for VLC and mpv. I don't want the string longer because it can create a wide UI on lower resolution monitors if you have 'Show more settings' enabled.

> Add "Save" button?

Yeah, I can see why people might find it useful but as you say it would bloat the interface.

> As I said it is common for me and friends to open the same file more than once, don't know about others though.

Why would you open the same file more than once?

**Comment by AtilioA** [comment]
Okay, great points everyone! As for:
> Why would you open the same file more than once?

as I said:
> from time to time I end up having to start Syncplay again, whether it is because I forgot to change some setting or because of some bug. 

A case in point: today I had to start Syncplay multiple times (my friend and I wanted to stream a video and he had a problem with youtube-dl, etc so we had to restart Syncplay multiple times for troubleshooting). We had to insert the video's URL each time. I don't see how this would bother someone who would never use the same video ever, but it could certainly help when one needs launch the same video.

**Comment by Et0h** [comment]
@AtilioA If someone is playing a file/stream you can double click on their entry in the list of who is playing what to play the same thing, so that is easily sidestepped. You can also use shared playlists. If you're the only one in the room just open the second instance before you close the first one.

**Comment by AtilioA** [comment]
That would do if e.g. the filename is the same which usually for me isn't the case

**Comment by Et0h** [comment]
@AtilioA If you open a second instance of Syncplay before you close the first instance then the filename/path should be the same as your initial instance. You can switch file on the second instance before closing the first instance.

**Comment by AtilioA** [comment]
> @AtilioA If you open a second instance of Syncplay before you close the first instance then the filename/path should be the same as your initial instance.

Just tried it and it doesn't happen :/

**Comment by Et0h** [comment]
> > @AtilioA If you open a second instance of Syncplay before you close the first instance then the filename/path should be the same as your initial instance.
> 
> Just tried it and it doesn't happen :/

Did you double click the file in the list of who is playing what? Is the file in one of your specified media directories?

**Comment by AtilioA** [comment]
Ah yes it works by clicking on the list but the path isn't set to the media file before starting Syncplay.

**Comment by Et0h** [comment]
I think this conversation has run its course. Thanks for sharing and discussing your ideas, it's always valuable to hear how people perceive the UI.
