### ISSUE TITLE
Crash at seemingly random point while playing video with syncplay 1.6.4

### ISSUE THREAD

**Issue by alxpettit** [Syncplay/syncplay#298]
Crash at seemingly random point while playing video with syncplay 1.6.4 on Arch Linux.
See [error output](https://gist.github.com/alxpettit/8b7add1e6be4402ac001ebdb679725b7). 

By my guess, is related to the media directory being set broadly (I set it to my home directory) and recursing over something unexpected.

**Comment by Et0h** [comment]
Is this fixed by #297?

**Comment by alxpettit** [comment]
@Et0h Oh, no. As far as I can tell, this is unrelated. #297 was just a warning that happens whenever you use '`is` instead of `==` for a comparison in Python3 -- as far as I know, it had no functional consequences.

**Comment by Et0h** [comment]
If you run Syncplay in --debug mode it might give you more information in terms of what it was doing just before it crashes. Not sure how well that works on Arch Linux.

**Comment by Et0h** [comment]
Is https://github.com/Syncplay/syncplay/issues/260#event-3232513393 of any use?

**Comment by alxpettit** [comment]
Sorry, the crash hasn't happened in awhile and it's kind of difficult to recreate on command. I've decided to create a wrapper script that always pipes STDOUT and STDERR to log and runs with `--debug` flag. Hopefully it'll happen again soon after I've done that.

**Comment by Et0h** [comment]
The issue seems to be that the thread to handle the media directory information updating includes a try but no except. This issue is hopefully resolved by commit 3125032e824803ab3a9d2295146defc2cde5932f to the extent that it should hopefully now just print a debug message if an error occurs rather than Syncplay stopping completely. This doesn't resolve the underlying question of why it was raising an exception, which seems to relate to the os.walk of the media directories. Maybe you have too many files in a directory, are specifying a network drive or removed media.

**Comment by alxpettit** [comment]
I haven't seen it happen again yet. I'll close this issue for now and reopen if it happens again.
