### ISSUE TITLE
Can't change font for MPV Chat

### ISSUE THREAD

**Issue by lilcsz** [Syncplay/syncplay#314]
I changed font but nothing happened please help me, I changed font because Ğ Ş ı letters not working
![321312](https://user-images.githubusercontent.com/43272857/82592222-4190ac00-9ba9-11ea-8a4c-abfd960fb436.PNG)

**Comment by Et0h** [comment]
Setting font worked for me, so I'd need more details about your set-up. For example, are you trying to set it to a font with a non-ASCII name?

That said, the reason that the Ğ Ş ı letters are not working is probably not due to the font, but due to the fact that in mpv you have to specify precisely which keys are accepted for the input chat. Please modify /syncplay/resources/syncplayintf.lua to add those letters. You can just open the file in a text editor which supports Unicode and add it to the end of the `non_us_chars = {}` list, e.g. by changing the line which is `≥','≠'` to read `≥','≠','Ğ','Ş','ı'`. Please let me know if that fixes it, because if it does then I can add that change to the Syncplay code.

If that doesn't work then it is an mpv or OS/library issue and I don't think there is anything we can do from the Syncplay side. However, you should be able to enter those letters within the Syncplay chat window.

**Comment by lilcsz** [comment]
Thank you very much It's worked, the code:
non_us_chars = {
	'А','а',
    'ą','ć','ę','ł','ń','ś','ź','ż','Ą','Ć','Ę','Ł','Ń','Ś','Ź','Ż',
    'à','è','ì','ò','ù','À','È','Ì','Ò','Ù',
    'á', 'é', 'í', 'ó', 'ú', 'ý', 'Á', 'É', 'Í', 'Ó', 'Ú', 'Ý',
    'â', 'ê', 'î', 'ô', 'û', 'Â', 'Ê', 'Î', 'Ô', 'Û',
    'ã', 'ñ', 'õ', 'Ã', 'Ñ', 'Õ',
    'ä', 'ë', 'ï', 'ö', 'ü', 'ÿ', 'Ä', 'Ë', 'Ï', 'Ö', 'Ü', 'Ÿ',
    'å', 'Å','æ','Æ','œ','Œ','ç','Ç','ð','Ð','ø','Ø','¿','¡','ß',
    '¤','†','×','÷','‡','±','—','–','¶','§','ˆ','˜','«','»','¦','‰','©','®','™',
    'ž','Ž',
    'ª','Þ','þ','ƒ','µ','°','º','•','„','“','…','¬','¥','£','€','¢','¹','²','³','½','¼','¾',
    '·','Ĉ','ĉ','Ĝ','ĝ','Ĥ','ĥ','Ĵ','ĵ','Ŝ','ŝ','Ŭ','ŭ',
    'Б','б','В','в','Г','г','Д','д','Е','е','Ё','ё','Ж','ж','З','з',
    'И','и','Й','й','К','к','Л','л','М','м','Н','н','О','о','П','п',
    'Р','р','С','с','Т','т','У','у','Ф','ф','Х','х','Ц','ц','Ч','ч',
    'Ш','ш','Щ','щ','Ъ','ъ','Ы','ы','Ь','ь','Э','э','Ю','ю','Я','я',
    '≥','≠≥','≠','Ğ','Ş','ı','ğ','ş'
}
Btw I don't need to change font now
