### ISSUE TITLE
{\\fscx0} appears when a " is sent in chat

### ISSUE THREAD

**Issue by ChiyoOsaka** [Syncplay/syncplay#329]
Syncplay version: 1.6.5 release 86
Python: 3.6.8
Pyside2: 5.12.3
 Qt 5.12.3

If you send, or recieve a message that has a double quote `"` in it, `{\\fscx0}` is added to the message.

Examples:

* `"` produces `{\\fscx0} "`
* `x " y` produces `x {\\fscx0} " y`
* `x " y " z` produces `x {\\fscx0} " y {\\fscx0} " z`

This might be an issue with mpv, but I'm not too sure [because of this line of code](https://github.com/Syncplay/syncplay/blob/aa5e7d8965f8ee4e97d60a54afb4cf5ffe5c8b9e/syncplay/resources/syncplayintf.lua#L38) and because `{\\fscx0}` [doesn't appear anywhere in MPV's repo](https://github.com/mpv-player/mpv/search?q=%7B%5C%5Cfscx0%7D&type=Code).

I have also found this issue in libass: libass/libass/issues/185 which may be related, but I'm not sure.

**Comment by Et0h** [comment]
Thanks for reporting this, it should be fixed now. The reason Syncplay uses {\\fscx0} is because that is how we get get long messages to wrap properly. See https://github.com/mpv-player/mpv/issues/4308 and https://github.com/mpv-player/mpv/issues/2203 for discussions of the issue and workarounds to it.

There is now a minor glitch where if you use a " and a \ in the same chat message it will show ＼ rather than \ but that's an edge case which I don't want to spend time trying to fix. For now I guess you can just consider it an Easter egg.
