### ISSUE TITLE
Syncplay pauses after every youtube video

### ISSUE THREAD

**Issue by Canageek** [Syncplay/syncplay#334]
Expected behaviour: When syncplay reaches the end of one video, it starts the next
Observed behaviour: When syncplay reaches the end of a youtube video, it pauses and needs to be manually unpaused. 

To duplicate: Using VLC or mpv (Other players not tested) load two youtube videos onto a syncplay playlist. Start the first one, observe how it does not advanced to the next video in the same manner as it does for local files.

**Comment by Et0h** [comment]
This has taken some time to work on because it involved in reworking some core Syncplay code and figuring out how best to update custom player-side interfaces. However, I now have PR #397 which hopefully resolves the issues you raised.

Please test the PR and let me know if it fixes your problems. I'm closing this issue so that the conversation can more to the pull request.
