### ISSUE TITLE
Cannot install on Ubuntu 18.04: python3-pyside2.qtwidgets (>= 5.12.0) not installable

### ISSUE THREAD

**Issue by technoabyss** [Syncplay/syncplay#335]
I'm trying to set up a syncplay server on headless 18.04 Ubuntu.

Running `sudo apt install ./syncplay_1.6.5.deb` gives me the following output:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'syncplay' instead of './syncplay_1.6.5.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 syncplay : Depends: python3-pyside2.qtwidgets (>= 5.12.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I'm not sure what I can do about this.

**Comment by technoabyss** [comment]
I ought to mention I managed to set up a server using the AppImage with the `--server` option.

**Comment by daniel-123** [comment]
This is expected. Pyside2 package which is required is not available in Ubuntu 18.04. Oldest Ubuntu version which includes Pyside2 and is compatible with Syncplay deb package is 19.10.

Appimage works because it bundles Pyside2 (and other things) within its binary.

**Comment by technoabyss** [comment]
fair enough. maybe this is a stupid question, but would it be possible to distribute the server binaries separately in releases?

**Comment by kathelynn** [comment]
> This is expected. Pyside2 package which is required is not available in Ubuntu 18.04. Oldest Ubuntu version which includes Pyside2 and is compatible with Syncplay deb package is 19.10.
> 
> Appimage works because it bundles Pyside2 (and other things) within its binary.

Source install also works assuming it requires Qtwidgets >=5.11.0 and no issues so far. Is it safe to match the requirements found in the deb file with the source requirements?

**Comment by daniel-123** [comment]
@kathelynn I think Ubuntu 18.04 doesn't have any qtwidgets version in repositories. At least nothing can be found in [official search](https://packages.ubuntu.com/eoan/python3-pyside2.qtwidgets). Development build of deb package on [bintray](https://bintray.com/syncplay/Syncplay/Syncplay/#files/) has also switched the qtwidgets dependency to include no version information as all versions should work with exception of 5.15 development version where pyside has a bug mentioned in #321.

For server installation technically pyside2 isn't required because there isn't any GUI anyway. I was thinking of creating a separate package with server components only, but I didn't know if there is any demand for it. I'm leaving this issue open for the time when I get around to setting up automation for building server package.

**Comment by daniel-123** [comment]
After some deliberation I decided that creating a separate deb package specifically for this purpose is not worthwhile given that there exist many alternatives.

If somebody else is willing to create such package integrated with our Travis builds, I'd be happy to merge the PR.

**Comment by technoabyss** [comment]
https://github.com/Syncplay/syncplay/issues/335#issuecomment-660227578
> fair enough. maybe this is a stupid question, but would it be possible to distribute the server binaries separately in releases?

Is this worth opening a new issue for?

**Comment by daniel-123** [comment]
Well, strictly speaking Syncplay doesn't need a binary distribution in first place - it's Python code that can be run as is.

With regards to server-only: technically indeed server needs a small subset of files from entire repository, but nobody so far has bothered to list them accurately. Entire codebase with all the icons is under 3 megabytes anyway. Full binary releases (Windows exe, Appimage and OSX dmg) include all dependencies inside (like entire Python3 environment) which is why they are comparably much larger. Deb doesn't include all the dependencies inside, but is set to require them upon installation. This is due to assumption that you will want to use the client with gui.

For server use I find it by far the simplest to just `git clone` the repository and run `sudo make install-server`. Though this still includes everything in repository with exception of client wrapper. You need to manually ensure that python requirements for server are met (python3 and python3-twisted, optionally TLS stuff).

With regards to opening new issue - I don't think there is that much use in separate binary distribution with server only. Based on assumption that whoever is running the server either is running it on their personal PC (where they also want the client anyway) or if they run it on their private server elsewhere, they can easily figure out whatever installation method they prefer. Because of that I don't think any of core developers feels pressure to implement it.

Because of all of the above I don't think opening a separate issue will be of much use. That said if you want to make a Pull Request which would integrate making a server-only package into our current Travis build system we could discuss it further :)
