### ISSUE TITLE
Feature request: Room history mechanism

### ISSUE THREAD

**Issue by Gbd199** [Syncplay/syncplay#336]
Provide a dropdown list with the names of previous rooms.
Requires configuration parsing changes/additions and gui logic enhancement.

**Comment by Gbd199** [comment]
Opened a pull request #337

**Comment by Gbd199** [comment]
Reopening for notice and feedback

**Comment by Gbd199** [comment]
@Et0h  Can you please take a look and share your thoughts?

**Comment by Et0h** [comment]
I've posted my thoughts to #337 and the discussion can continue there.

**Comment by Et0h** [comment]
Okay, so I've accepted #337 and tweaked it with 3c7ca9706d7dfb00d7e1a84ebae7a534d54d42b9

Some things to note about changed from #337 (and a few requests for feedback):
* For now I've made it so that you have to manually add rooms to the room list. There could be an optional in the future to allow for rooms to be automatically added, but it would then add complexity to the GUI so it might be fine just leaving it as manual.
* I've renamed it 'room list' rather than 'room history' as it is a user-editable list, not just a history.
* I've added the combo box to the main GUI and added the option to change the room list to the 'window' portion of the menu bar. I didn't add it to the main GUI because I didn't want to add too many options there (as it). However, I could add a "Show edit room button" option to the Window menu (off by default) if people wanted, in line with what I do for playback controls and auto-play buttons. Thoughts/opinions?
* I've moved the edit button in the config window to the right to be more in line with normal UI conventions (even if it is less space efficient).
* For now I've not changed it to automatically change the default room to the last one you joined as I'm not sure if that's the behaviour most people want. Thoughts/opinions?

**Comment by Et0h** [comment]
Changes:
* Room names are now saved by default, this is changeable in the "Add rooms you join to the room" list option in "Misc". I was thinking that it could be the same option for if we have an option in the future to save server addresses.
* When you create a managed room, it also saved the version of the room name which includes the room password.
* Room names are now listed alphabetically. Previous behaviour was to have the most recently joined rooms at the top.

Happy for feedback on both of these changes.

**Comment by Et0h** [comment]
As this feature has now been introduced in Syncplay 1.6.7 I will close this issue. Thanks to everyone who has contributed!

**Comment by Gbd199** [comment]
Very welcomed changes and decisions. 
Thanks a lot for advancing the issue @Et0h! Awesome to see the mechanism in an official version
