### ISSUE TITLE
Support celluloid as player

### ISSUE THREAD

**Issue by soredake** [Syncplay/syncplay#343]
https://celluloid-player.github.io/
Based on mpv.

**Comment by Et0h** [comment]
As a general rule we don't add support for media players that we don't use, because it is only from using Syncplay with that media player that issues can be identified and fixed and if we supported everything then it would create an increasing burden on Syncplay development.

As such, I'd be happy to provide to support to anyone wishing to add support for a new media player, but they would need to use that media player on a regular basis and be willing to maintain that support in the long term.

Depending on how they are coded some mpv-players can be easily supported, but others would need to be modified to be significantly modified to support Syncplay.

**Comment by Et0h** [comment]
I'm closing this issue as nobody has volunteered to implement the requested feature. If someone does decide to work on this idea then feel free to ask for this issue to be re-opened.

**Comment by CaptainJawZ** [comment]
I've been watching movies on a weekly base for over a year with a bunch of friends (who would also use celluloid). I'm not the most proficient developer, but I'm competent enough with Python, and given how Celluloid is just a frontend to MPV (which i think accepts the same flags from the terminal), I volunteer to support. With me and my friends using it weekly, I'd iron out any bugs presented by newer versions of the player.

**Comment by Et0h** [comment]
Thanks for volunteering to help out @CaptainJawZ - if you want to make a PR for Celluloid support then that would be welcome.

A starting point for how to do it would be to look at mpv.net at https://github.com/Syncplay/syncplay/blob/master/syncplay/players/mpvnet.py

As you can see from https://github.com/Syncplay/syncplay/commit/187c8d87fc369faa9b0a71715f771b94ea9810fc we also add player paths and an icon path to `syncplay/constants.py` and import the player in `syncplay/players/__init__.py`

Some mpv frontends allow for full pass-through of command line switches and messages to mpv as if it were mpv and some do not. As such, just because something is a frontend to mpv doesn't always mean it will simply work with Syncplay. Sometimes what we've had to do is work with developers on the player-side of the equation so it support Syncplay.

**Comment by CaptainJawZ** [comment]
Hello! so I've got myself a bit stuck, I hope it is ok to ask for help in here. 

So I modified constants.py and __init__.py to add the variables that would be required for celluloid.

Now, celluloid can parse any MPV flag so long as it begins with --mpv-
so for instance --force-window=yes would become --mpv-force-window=yes, and so on

In order to achieve this, I added a few placeholder lines (probably there is a better way to do it) on celluloid.py (which is a modified copy of mpvnet.py

```python
    def run(client, playerPath, filePath, args):
        constants.MPV_NEW_VERSION = True
        constants.MPV_OSC_VISIBILITY_CHANGE_VERSION = True
        for mpv_arg in MpvPlayer.getStartupArgs(args):
            celluloid_arg = "mpv-" + mpv_arg
            MpvPlayer.getStartupArgs(args)[celluloid_arg] = MpvPlayer.getStartupArgs(
                args
            ).pop(mpv_arg)
        return CelluloidPlayer(
            client, CelluloidPlayer.getExpandedPath(playerPath), filePath, args
        )
```
The way this works on my head, is it would simply append the suffix mpv- to every key on the list of arguments that get passed to MPV.

While this suppresses any errors from celluloid, it still fails to open, and gives some errors which relate to clientManager.py client.py and internet/base.py

the errors are as follow
```
Traceback (most recent call last):
  File "/home/jawz/Development/Git/syncplay/syncplay/clientManager.py", line 16, in run
    syncplayClient.start(config['host'], config['port'])
  File "/home/jawz/Development/Git/syncplay/syncplay/client.py", line 878, in start
    reactor.run()
  File "/usr/lib/python3.10/site-packages/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
  File "/usr/lib/python3.10/site-packages/twisted/internet/base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python3.10/site-packages/twisted/internet/base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/jawz/Development/Git/syncplay/syncplay/players/celluloid.py", line 29, in run
    for mpv_arg in MpvPlayer.getStartupArgs(args):
```

as I am getting familiar with the code still, I was wondering if you could orient me as to what scripts to look at for when the player is called, and what other parts of the script add arguments to the player, since i'm assuming the error happens because of arguments which the .lua script requires to run, perhaps there is a better part where I can place the suffix function, I'll try to keep it away from mpv.py as much as possible.

**Comment by Et0h** [comment]
It's been a while since I've had to work with the mpv arg code so I might have got some things wrong but my understanding is as follows:

The Syncplay-modified version of the MPV JSON IPC takes an args argument from mpv (or mpvnet/celluloid) which it then passes through to our custom _get_arglist function. This begins by setting idle, input_ipc_server, input_terminal and terminal values if they are not otherwise set and then extends it with the args from Syncplay. See: https://github.com/Syncplay/syncplay/blob/master/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py#L216 and https://github.com/Syncplay/syncplay/blob/master/syncplay/vendor/python_mpv_jsonipc/python_mpv_jsonipc.py#L245

As such, to prepend all of the args you would need to modify the function of self._get_arglist in python_mpv_jsonipc so that when you are using celluloid it prepends the names of all the arguments (default and user-specified) with "mpv-".

**Comment by soredake** [comment]
@CaptainJawZ if you can also support https://invent.kde.org/multimedia/haruna it would be really nice.

**Comment by CaptainJawZ** [comment]
Apologies, I could've written this month's ago, since this is something I noticed the day I began trying to implement Celluloid into syncplay, but I didn't want to give up immediately, so I let the project on idle while I became more proficient (+ there were periods of time where life kept me very busy).

But now after spending some more time looking into this, doesn't seem like implementing this into celluloid is possible, while Celluloid pretty much is compatible with every MPV command, it cannot load scripts the way that syncplay would require, I tried doing some hacky stuff trying to setup a IPC socket, similar to how jellyfin-mpv-shim does it, but didn't had any luck getting Celluloid to play along. So I think for the moment it is not possible, perhaps in future builds of Celluloid, I do intend to look into this again in the future, but for the time being my hands are tied.

**Comment by soredake** [comment]
@CaptainJawZ haruna cannot be supported too?

**Comment by CaptainJawZ** [comment]
@soredake same boat, can't receive MPV commands through command line, and through the gui, you can' attach the script file required for syncplay, only basic MPV functions like controlling volume, shortcuts, etc.

**Comment by soredake** [comment]
@CaptainJawZ thanks for trying! I'll close it for now.

It would be nice if you can please try adapting syncplay code to flatpak (with the help of flatpak-spawn), https://github.com/Syncplay/syncplay/issues/199#issuecomment-1135659633
