### ISSUE TITLE
Kodi support? Alternatives?

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [Syncplay/syncplay#350]
Hi,

Sorry if this question as already been answered but I didn't find any, so I'm asking here.

I own a Jellyfin Server, which I share to friends. It works perfectly. But now we are looking to watch movie toguether via Syncplay. Already tried it with VLC, and it works great.

I know there is already a syncplay feature built in Jellyfin but it only works with movies played in the web version of Jellyfin. Unfortunately, 90% of my library is x265 encoded so it can't be played via the web UI. It only works when played with Kodi and its addon. So we all have to use Kodi.

But Syncplay is not compatible with Kodi so we can't use my server to watch movies together.
I am looking to find a solution for that, but after days of research, I didn't find anything. I find that very strange, because I guess movie playback syncing is something A LOT of people are asking for. But there is very little solutions available. Syncplay is one of them, but not for Kodi.

Is Kodi support planned ? Is there a addon that could do that ? Is there alternatives to Syncplay that could work for us ? Is there other solutions I may not have heard about ?

Thanks in advance for your help,
Have a good day.

**Comment by Et0h** [comment]
It is noted at https://syncplay.pl/about/ideas/ that: "[Support for] additional media players would need to come from an individual who used that media player and was willing to maintain it, and may require modifications to the media player software itself."

Syncplay is an open source project run by unpaid volunteers. Anyone can contribute but nobody is forced to do. As such, the 'supply' (i.e. what people are willing/able to do) is at least as important as 'demand'. Usually people contribute features that they themselves want to see in Syncplay, and because they then use that feature they are able to identify problems and fix them as they arise (e.g. it is not uncommon for media players to change things in new versions which breaks Syncplay compatibility).

Back in 2015 Tari gave adding Kodi support a go but the project stalled. See https://github.com/tari/syncplay/commits/kodi-support and https://github.com/Syncplay/syncplay/pull/77

Back in 2016 someone asked for volunteers at https://forum.kodi.tv/showthread.php?tid=213926 for someone to take over the effort but nobody stepped forwards.

Nobody is currently volunteering to introduce and maintain Kodi support, and so it isn't happening. I'll leave this issue open for a while to see if anyone will volunteer for this project, but as I don't use Kodi I am not the right person to lead this project.

**Comment by Et0h** [comment]
This topic has been open for more than a month and nobody has volunteered to introduce and maintain Kodi support. As such, I'll close this issue for now but if someone comes along who wishes volunteer then feel free to re-open the discussion.
