### ISSUE TITLE
Feature request: Changing chat timing and position

### ISSUE THREAD

**Issue by NotNate** [Syncplay/syncplay#351]
It would be nice for an implementation of the ability to move not only the chat input area to the bottom, but where the messages come in as well. The chat messages also sometimes disappear too quickly to read, so it would be nice for a change of the delay to be added before it disappears.

**Comment by Et0h** [comment]
There are a lot of chat settings which can be changed if you modify the [gui] section of syncplay.ini / .syncplay file (in %APPDATA% in Windows). Options includes: chatmaxlines, chattopmargin, chatleftmargin, chatbottommargin, chatmoveosd, chatosdmargin, notificationtimeout, alerttimeout, chattimeout. I've not done much testing on changing these, so let me know if it works.

The only thing I know you can't do is to reverse the logic of text so that the most recent text is at the bottom rather than the top. If anyone can think of an elegant way to add that support to syncplayintf.lua then feel free to make a pull request.

**Comment by Et0h** [comment]
No immediate plans to implement any changes.
