### ISSUE TITLE
frequent jumping

### ISSUE THREAD

**Issue by AustinSumigray** [Syncplay/syncplay#354]
For the last couple months we've been seeing an issue where the video playing will just jump back and forth leading to video playing to be unusable. 
![image](https://user-images.githubusercontent.com/8961217/93647811-51918e80-f9d7-11ea-833b-32e8e36a3469.png)
![image](https://user-images.githubusercontent.com/8961217/93647895-7980f200-f9d7-11ea-8d2c-32a95e15d7a5.png)
This is what both of our configurations are currently set to, so shouldn't it not be causing rewinds? Were both on latest syncplay latest VLC. Thank you.

**Comment by Et0h** [comment]
What do you define as the latest VLC? What is the filename of the files you are playing?

There are some reasons why https://syncplay.pl/ recommends that people use mpv as their media player such as mpv's support for in-window chat and improved support for streaming videos. However a major reason we don't recommend VLC for use with Syncplay is that it is generally unreliable at actually reporting to Syncplay the current playback position. We rely on the value of the time variable from VLC, but this is not always actually updated by VLC and so the values it gives can be out of date and so we have to have a lot of code for ignoring the position and assuming the value from the previously given position - but this is not always good enough to prevent issues. The problemcan be worse on newer versions of VLC and when playing certain formats (VLC is more accurate at reporting time with MKV, worse with MP4 and AVI).

As such, those annoyed with these issues should either raise concerns with the VLC team or becoming a VLC developer to fix the issue because for now all we can really do to reliably resolve the issue is to advise people to use mpv if they have issues with VLC.

**Comment by Et0h** [comment]
As I have added warnings for erroneous seeks in VLC and have not had any response on details of how to reproduce the issue then I consider this matter closed for now as there is nothing more that I can do at this stage. If people experience this problem in the future then they can re-open the issue and post the relevant information.

**Comment by jeroen7s** [comment]
Is there any bug report at VLC side to get this inaccuracy fixed?

**Comment by Et0h** [comment]
> Is there any bug report at VLC side to get this inaccuracy fixed?

Hi @jeroen7s  I think it might be this issue here: https://code.videolan.org/videolan/vlc/-/issues/22456

Last I checked VLC 4 wasn't stable enough on Windows to make it worthwhile trying to get a proper updated version of the Syncplay lua interface script script for VLC (because it was too hard to test if any issues related to the script of the instability of VLC 4). I'll probably revisit it some day when VLC 4 is closer to release (or someone else might revisit it first to create a working VLC 4 version of the Lua interface script).

Our advice for those experiencing problems is to use the mpv media player (which is more reliable for syncing, has better stream compatibility if you use youtube-dl, and supports in-player chat and multi-line notifications and chat messages).

**Comment by jeroen7s** [comment]
Thanks for the link, i'll be keeping track of progress on there
I'm already using MPV for this but my friends are used to VLC and don't like to install another one :D
