### ISSUE TITLE
Suggestion: Make a server only package

### ISSUE THREAD

**Issue by tippl** [Syncplay/syncplay#375]
I was setting up a server instance for Syncplay on a server. When i attempted to install the .deb package, the hard dependency on vlc/mpv makes the package manager want to install the whole dependency chain for that (X11 server among other things).

This is really not ideal when trying to install just the server, i don't want to install X11 on a headless machine somewhere in cloud. I solved this by repackaging the deb file and removing the vlc/mpv and pyside2 dependency.

My suggestion is, that there should be a server only package so that you don't have to repackage, but still get the benefits of using a package manager.

**Comment by Et0h** [comment]
I believe the discussion at #335 is relevant, especially the comments by @daniel-123. Linux isn't my area, but my understanding is that if someone is willing to implement and maintain support for a server-only package then they are free to make a PR. You would probably want to wait for PR #374 to be resolved before trying to make a PR implementing this feature, though.

**Comment by daniel-123** [comment]
Because you are second person to ask about this, I actually think that there is enough demand for such package to bother me enough to get around and make it.

Though like @Et0h said - we are currently right in the middle of migrating entire CI process over to different provider in #374 so this will have to wait.

Right now I'm thinking of simply making a no-gui version since that's only matter of removing dependencies and won't require any significant modification to the build script: https://github.com/Syncplay/syncplay/blob/master/travis/deb-script.sh

Last tidbit I'd mention is that server code hasn't been really touched for a good while. Only change it had in recent years is adding TLS support and that's it.

**Comment by Morsine** [comment]
I've been looking for such thing as well!

**Comment by tcyrus** [comment]
I made a fork of syncplay which removed all the client side code a while back. Ii isn't neat, and I changed a large chunk of the code to work with my specific use case, but it's [here](https://github.com/weeb-poly/syncplay-server) if you want it.

**Comment by daniel-123** [comment]
@Morsine @tippl I've made a pull request with server package. Could you test the results? You can download the zip with both server and full packages here: https://github.com/Syncplay/syncplay/suites/1888847905/artifacts/36933740

The package is architecture independent, so it will work on Raspberry Pi as is.

**Comment by tippl** [comment]
@daniel-123 Just tested it on my server. Works great, does not require the gui packages, starts and i'm able to connect to it. I see no issues with it.

**Comment by daniel-123** [comment]
Implemented in #382
