### ISSUE TITLE
Syncplay client does not trust wildcard certificate

### ISSUE THREAD

**Issue by Vulpes-fox** [Syncplay/syncplay#385]
I created a certificate with let's encrypt that uses a wildcard `*.example.com` and configured the TLS, but when I connect from the client the chat/console outputs:
```terminal
[20:16:15] Successfully reached example.com (<ip>)
[20:16:15] Secure connection established (TLSv1.3)
[20:16:15] Syncplay does not trust this server because it uses a certificate that is not valid for its hostname.
[20:16:15] Disconnected from server
```

**Comment by albertosottile** [comment]
Syncplay uses standard certificate validation tools. However, it could be hard to debug this issue because Syncplay uses Opportunistic TLS, hence it does not expose the certificate by default. So, I would advise you to set up a TLS-enabled web server on the same domain and try to connect to it with a browser, then verify that the browser accepts the certificate.

If that works, you can then try the same verification chain we use in Syncplay by running the snippet included here: https://service-identity.readthedocs.io/en/stable/api.html

**Comment by Vulpes-fox** [comment]
Changing the certificate domains to `example.com` and `*.example.com` solved the issue.
It now works for the main domain and for any subdomain.
