### ISSUE TITLE
Update info & build a little bit more packages (Fedora, Flatpak)

### ISSUE THREAD

**Issue by sxiii** [Syncplay/syncplay#386]
Some small ideas that can be implemented pretty easily:

- [ ] 1. The Fast And Easy Fix: To downloads section, you probably should add link to ArchLinux AUR for SyncPlay: it works perfect on 3 different OSes (Manjaro, Arch and EndeavourOS). This will help a lot of people who uses Arch & Manjaro which is a large audience: https://aur.archlinux.org/packages/syncplay/
- [ ] 2. There's no RPM package, sadly. I'd be happy to help and package it, although I don't have too much RPM packaging experience. This is second large audience.
- [ ] 3. The package in SNAP (https://snapcraft.io/syncplay) is v.1.6.5 which is outdated. I don't know whom to ping to update it.
- [ ] 4. Last but not least, there's Flatpak. It would be nice to do that as well.

So I wonder if Syncplay uses some scripts when the build are updated or not? 

I might grasp on one point or another from that exact list.

**Comment by daniel-123** [comment]
1. AUR package is not maintained by any of the core Syncplay developers. This is why it was never featured in the downloads section.
2. RPM package might be tad difficult because Github Actions only run Ubuntu. That said, a basic package could maybe be created from the existing deb using Alien (deb-rpm converter).
3. SNAP worked on previous CI pipeline which was using Travis. We tried to make a SNAP package work with Github Actions and recent Syncplay versions, but in general it proved to be *way* more difficult than it should be. We never managed to produce a package that would work without segmentation faults on substantial fraction of systems we tested it on. As far as we are aware there is just no easy and well supported way of packaging pySide2 applications into SNAPs. All of this has lead to decision to drop SNAP in future.
4. When we looked at it last time Flatpack has pretty restrictive sandboxing which makes it very difficult if not outright impossible for Syncplay to communicate with media player. Making it work would likely require packaging a media player together with it, which gets very complicated not just for technical reasons but also possibly licensing.

As more of a side note - we have an AppImage which should work almost anywhere. This in one way or another covers most of the needs that would be addressed with RPM/SNAP/Flatpak.

Lastly - the biggest problem in all of this is matter of ownership and maintenance. Most of the packaging methods currently in the CI pipeline are used on regular basis by core Syncplay developers. We would like to avoid situation where a packaging pipeline we barely understand (and don't really test ourselves) is introduced as it also carries expectations of maintaining it in good shape.

**Comment by sxiii** [comment]
1. Ok, I see.
2. Yeah, I know alien, this is kinda one-time solution; I was thinking to have a permanent one.
3. Oh. I've actually just tried to build SNAP, and it seems it worked. I haven't tested it yet, but this is it: https://snapcraft.io/syncplay-latest -> the process of making the package was easy and straightforward, if we'll see it's working fine, I might share it somewhere as an article.
4. Oh yes. I see. This is sad.

Yes, I am using AppImage on some machines and it works. I was just curious to see the package in different distributions formats because I see it as very finished and polished, and important. That could lead to larger user- and dev- base in the future.

About last point, I understand and totally agree with this position. Maybe we could implement something of the SNAP. Thanks for your fast answers and good luck with development!

Den

**Comment by daniel-123** [comment]
@sxiii I've tried your snap, but it seems to error out:

    $ snap run syncplay-latest.syncplay
    WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
    Traceback (most recent call last):
      File "/snap/syncplay-latest/2/usr/bin/syncplay", line 16, in <module>
        from syncplay import ep_client
    ModuleNotFoundError: No module named 'syncplay'

Maybe I'm running it in wrong way - I don't really have any experience with snaps.

Also it seems like I missed your initial question about scripts used in CI pipeline - with one exception, they are all referenced in [https://github.com/Syncplay/syncplay/blob/master/.github/workflows/build.yml](our build workflow for Github Actions). The exception is [Windows build](https://github.com/Syncplay/syncplay/blob/master/.appveyor.yml) which uses AppVeyor for historical reasons.

With regards to rpm, our deb package is also rather basic (i.e. it doesn't fully conform to Debian Policy). So an alien-generated rpm package would probably be just as good. Only concern I'd have is that the dependencies might have different names - especially with regard to python packages.

**Comment by sxiii** [comment]
@daniel-123 me neither have about zero experience with snaps. Maybe I've done something wrong :) I will probably try to fix it a bit later.

Ok I see your point on the RPM thoughts. Thanks :)

Should I close the issue meanwhile?

**Comment by daniel-123** [comment]
I guess the issue can be closed with following status:

- We haven't managed to create a process which would result in reliable Snap package. In light of recent inclusion of Synpcplay into Debian repositories and working AppImage - Snap is basically redundant and on its way out as far as distribution channels of Syncplay go.
- I would be open to officially including RPM only if somebody would be actually using it on daily basis and they step up to committing to maintaining it.
- Unless somebody comes forward and convinces us otherwise, Flatpak is not really compatibly with how Syncplay works right now.
- We'll think about reworking installation/downloads part of web page. Especially with inclusion of deb package it probably warrants some rearranging.

**Comment by sxiii** [comment]
Thanks @daniel-123 for the clarification. I agree with your points and as so, I'll close the issue. :+1:
