### ISSUE TITLE
Manpages for client and server

### ISSUE THREAD

**Issue by Fuddl1** [Syncplay/syncplay#387]
Hi,

for the Debian package I wrote two simple manpages, one for the client and one for the server. Please feel free to adapt and include them. You can find them here:

- https://salsa.debian.org/fuddl/syncplay/-/blob/master/debian/syncplay-server.1

- https://salsa.debian.org/fuddl/syncplay/-/blob/master/debian/syncplay.1

Cheers,
Bruno

**Comment by daniel-123** [comment]
Hello @Fuddl1 

Thank you for making the effort to package it on Debian. I personally really appreciate it since in the past I kinda wanted to try it, but always found the process to be a bit daunting. Ultimately I only created a very rudimentary deb packages.

I'll try to incorporate the manpages into current package our CI process is making.

If you think there are any changes or additions to the repository that would make packaging Syncplay for Debian easier, feel free to ask about them.

**Comment by Fuddl1** [comment]
> Thank you for making the effort to package it on Debian. I personally really appreciate it [...]

My pleasure, I'm glad to read that :)

There were no obstacles to package it, only one minor patch was necessary but it's not related to this ticket.

**Comment by Et0h** [comment]
Thanks for your work on this @Fuddl1 

One problem I noticed at https://salsa.debian.org/fuddl/syncplay/-/blob/master/debian/syncplay.1 is:

```
.TP
.B \-g, \-\-force\-gui\-prompt
Einstellungsfenster anzeigen
```

Please note that this is the German description. The English text is: `make configuration prompt appear` or `Force configuration window to appear when Syncplay starts.`

People who want further detail on using Syncplay could be directed to:
- The Syncplay installation guide: https://syncplay.pl/guide/install/
- The Syncplay client guide: https://syncplay.pl/guide/client/
- The Syncplay server guide: https://syncplay.pl/guide/server/
- The Syncplay troubleshooting guide: https://syncplay.pl/guide/trouble/

**Comment by Fuddl1** [comment]
Oops, a copy-paste mistake. I fixed it in the Debian packaging repository.

Thanks for pointing it out, @Et0h
