### ISSUE TITLE
Bitdefender detected Gen:Variant.Razy:843368 in syncplayServer.exe Windows Ver 1.6.7

### ISSUE THREAD

**Issue by Shrek-SC** [Syncplay/syncplay#391]
This was only detected after I installed Syncplay using the installer version on my PC. The installer itself was clean when scanned.

Screenshot: https://imgur.com/a/jQVvR9B.

This seems to be contrary to what is on the virustotal page: https://www.virustotal.com/gui/url/b7ebb12e108eb6005f9ac539a49ce46e4f5e17cf0ef0587de75a7cd061805a4f/detection

Edit:

I've done a full scan of my PC and nothing else has been detected anywhere, and when I restarted the PC it came up with "your security solution is cleaning...success!" (it disappeared too fast for me to read it properly, but it was in the black and white bios font).

**Comment by Et0h** [comment]
I have now submitted a false positive report via https://www.bitdefender.com/submit

**Comment by Et0h** [comment]
I reported the false positive which is a problem with BitDefender rather than Syncplay.

I've just tried specifically scanning syncplayServer.exe via VirusTotal.com and it says BitDefender reports it as clean:.

As such, I'm closing this issue. If you have any further issues with BitDefender then please contact BitDefender.
