### ISSUE TITLE
Installing on a fresh Crostini container (chromebook's Linux)

### ISSUE THREAD

**Issue by kathelynn** [Syncplay/syncplay#393]
Debian 10.8 with Python 3.7.3 and Syncplay 1.6.7

This being a dependency problem than Syncplay distribution problem, but I thought I would report this to those that are having problems and also wondering if there's something that can be done:
- Running a .deb file will only lead to crashes with no errors, which means users will have to debug.
- Cryptography and pyasn1 python modules are out-of-date
- libxcb-util.so.1 is missing

Fixing this issue:
```
python3 -m pip install cryptography pyasn1 --upgrade
curl -O http://ftp.us.debian.org/debian/pool/main/x/xcb-util/libxcb-util1_0.4.0-1+b1_amd64.deb
dpkg -i libxcb-util1_0.4.0-1+b1_amd64.deb
```

Not sure if this is exclusive to Crostini or a Debian distribution issue.

**Comment by daniel-123** [comment]
I've done some digging and in general those seem like Crostini problems.

From my testing on Debian 10.8:
- TLS just works despite not touching cryptography/pyasn1
- command line interface is fully functional
- For working GUI it's necessary to update pyside2 to version 5.12+. Upgrading it *specifically* to 5.15.2 (latest version) results in it complaining about missing libxcb you mentioned.
Missing libxcb, curiously enough is also a problem when using AppImage on Debian 10.8

I've got no clue how Crostini containers work, *but* thanks to your fixes there I managed to find a functional workaround for non-usable GUI on Debian 10.8

**Comment by daniel-123** [comment]
From what I read [here](https://chromium.googlesource.com/chromiumos/docs/+/master/containers_and_vms.md) Crostini "Debian" is not quite Debian.

Your workarounds aren't exactly feasible to be included in the deb package itself.

Lastly - Debian 11 is slowly materializing on the horizon and [Syncplay is in the official repositories](https://packages.debian.org/bullseye/syncplay) there. So I'm not sure if spending substantial amount of resources on making current version compatible with Crostini Debian 10 is even worthwhile.

Because of that I'm thinking about closing this issue unless you have some solid ideas about what could be done to improve situation without making any large changes to our current distribution pipeline.
