### ISSUE TITLE
[Feature request] Allow closing player window without exiting Syncplay

### ISSUE THREAD

**Issue by Gieted** [Syncplay/syncplay#407]
It's very confusing that by closing player, you are also closing Syncplay. Why don't you make it, so the player could be closed, and then it would be reopened after changing a file?

**Comment by Et0h** [comment]
I don't see why this would be a desirable change. Why do you want it?

**Comment by Gieted** [comment]
I'm closing player window by mistake all the time, my friends say this also happens to them often

**Comment by Et0h** [comment]
As far a I can see this is not a Syncplay problem, and any change from Syncplay's side would be difficult to code and suboptimal. 

If you want the media player to add an "are you sure you want to quit?" dialog box then you should suggest that to the authors of the media player (or you could could code it yourself if you are able to do so). If the media player already has that option then you should enable it. On a wider point, you might and your friend want to reconsider whatever usage pattern you are using which is being interpreted by the media player as an attempt to close it. You might also be able to find software for your operating system such as 'NoClose' which can intercept close requests.

I'll leave this issue open for a while for if you want to talk more about how you keep accidentally closing the window and for if others want to give advice, but given the significant amount of work required to change anything on the Syncplay side (compared to on the media player side) this is not a change I think should be a priority for Syncplay.

**Comment by Gieted** [comment]
You misunderstood me. By saying that I close the player accidentally I haven't meant that I do by some sort of miss click, but rather I'm purposefully closing a player window after a video I've been watching has ended, because it's a normal thing I do with windows that are no longer needed, however this also causes closing Syncplay window for some reason. 

It's very unexpected that closing one window also causes another window to be closed. It's as if you have opened a Word document using a file explorer and closing Word would also close the explorer, it's just counterintuitive. I can understand that closing a player automatically when you close Syncplay is somewhat convenient, but I don't understand why anyone would like it to also work the other way and close Syncplay by closing a player.

My proposal is to make it, so player window wouldn't be opened at all before selecting a first file in Syncplay, closing it wouldn't close Syncplay and selecting a file in Syncplay either plays it in an already opened player instance or starts a new one if it's closed. This would be much more natural behavior than what it is currently.

**Comment by Et0h** [comment]
Thank you for explaining your position on why you think the behaviour should be as you requested.

The current behaviour works exactly the way that I and other founding developers intended, and as such has become the established practice in Syncplay for the decade or so that this programme was first released. I am not aware of anyone having raised concerns about this behaviour before over this extended period. Given the amount of work it would take to change the behaviour, the established nature of the behaviour, and the lack of problems reported by the general userbase over the past decade I think that this is going to be an area where we will have to agree to disagree.

I appreciate that once formed habits can be harm to unlearn, but if you are playing multiple videos then I would advise that you to use the shared playlist feature rather than closing the media player to open a different file. If you set it up correctly, you should be able to leave the media player maximise throughout playback and never even think about closing it. Indeed, if you use mpv then you can even carry out text-based chat from within the media player, and you can use that chat facility to carry out commands if you wish which makes the Syncplay window almost redundant during playback.
