### ISSUE TITLE
Yes I know this may sound stupid but my beginner brain does not understand

### ISSUE THREAD

**Issue by ThomasDurham** [Syncplay/syncplay#413]
Hey,

I am just wondering how to specify or know the password to identify as the room operator, this wasn't written in the docs so I am not a 100% sure on what to do, if you have any ideas, please let me know.

**Comment by Et0h** [comment]
Managed rooms are a bit complicated to figure out at first, but once you get it working they can be quite useful for large watch parties.

First off, if you look at the help guidance at https://syncplay.pl/guide/client/ it explains:

> Several features are available under the ‘Advanced’ section of the menu bar at the top of the Syncplay window:...
>
>**Create managed room / Identify as room operator** – In a managed room only those identified as ‘Room Operators’ people can pause, unpause and seek. If you create a controlled room then you will join the ‘managed’ version of that room (e.g. ‘+MyRoom:df908ee00155’) and will be given a password for that controlled room (e.g. ‘QY-907-577’). You and others can use this password to identify yourselves as Room Operators on that specific room in the future. Room Operators are identified in the userlist by an icon of a person holding a key. Room name/password combinations only exist for the server you created the room on, so if you change server you will need to generate a new room suffix.

When you select the option from the advanced portion of the Syncplay menu to create a managed room it will say something like the following in the notification window:

> Created managed room '+Foobar:1E11B7F6F62A' with password 'NH-839-939'. Please save this information for future reference!
> 
> In managed rooms everyone is kept in sync with the room operator(s) who are the only ones who can pause, unpause, seek, and change the playlist.
> 
> You should ask regular viewers to join the room '+Foobar:1E11B7F6F62A' but the room operators can join the room '+Foobar:1E11B7F6F62A:NH-839-939' to automatically authenticate themselves.

So in this example `+Foobar:1E11B7F6F62A` is the public name of the room and `NH-839-939` is the password used to authenticate operators. As explained in the notification, when you combine the two as `+Foobar:1E11B7F6F62A:NH-839-939` you can join the public room but auto-authenticate with the password.

There is also a nice little additional feature which I think was introduced in Syncplay 1.6.6 (but has never been properly documented), which is that the managed room feature is made even easier due to the 'room history' / 'favourite rooms' feature. Recent versions of Syncplay will automatically add both `+Foobar:1E11B7F6F62A` and `+Foobar:1E11B7F6F62A:NH-839-939` to your room list which is shown in the dropdown list on the configuration window (the default room option) and in the main Syncplay GUI (next to where it says to join the room). If you join using the latter (longer) room name then it will automatically authenticate you as the room moderator for that room. To backup your list of rooms and passwords you will want to backup the syncplay.ini in the %APPDATA% folder (or equivalent if you are using a non-Windows operating system).

**Comment by Et0h** [comment]
I'll close this as I think I've answered your question adequately, but feel free to re-open it if you have any follow-up queries.
