### ISSUE TITLE
[Feature request] Desktop notifications when mpv or syncplay windows are unfocused

### ISSUE THREAD

**Issue by prez** [Syncplay/syncplay#420]
Not sure how feasible this is, but Qt notifications would certainly be very useful. 
However, I don't think it makes sense to show them when either the player or the syncplay window is in focus.

**Comment by daniel-123** [comment]
This could be a possible enhancement to how Syncplay works, however just like any other UI feature it will require a lot of effort in figuring out how exactly it should work before even starting to think about how to implement it in code. After such discussion somebody would likely need to make a PR as no one among core developers has much time nowadays.

We would need at least a few user stories for how this feature could behave in different circumstances.

For example my own usage is very far from being representative, but I wouldn't get much use from such notifications:

- I have my window manager configured so that window focus follows mouse and window focus doesn't bring the window to the front. Because of that it's very easy and common for me to have focus on some other window than Syncplay/mpv even while I'm actively using them.
- I use Syncplay along with voice chat, so the random chatter and the very fact that I can hear video playing do serve similar purpose as a notification would. It's also easy for me to keep the mpv window on top while I wait for everybody else despite it having no focus.

**Comment by Et0h** [comment]
This isn't a feature I would use, so that means it wouldn't be a good feature for me to develop and maintain. I'm not sure what your intended use case is and what you would want notifications about .

**Comment by prez** [comment]
I understand, feel free to close then.
I mainly wanted chat notifications because I am only using syncplay with voice chat half of the time, and it's easy to miss new messages when waiting for other people to get ready.
