### ISSUE TITLE
display youtube title

### ISSUE THREAD

**Issue by rhetr** [Syncplay/syncplay#424]
when you load a youtube url into syncplay it should automatically grab the video title

**Comment by Et0h** [comment]
The media player will display the video title. In terms of Syncplay, it refers to the video by the URL because that is what it consistently knows and what can be used to switch to the video.

However, what you can manually add something to the end of the video, e.g.:
https://www.youtube.com/watch?v=abc-de#Cat Video

**Comment by rhetr** [comment]
does syncplay have the ability to display the title though? i navigate the playlist through syncplay, not the media player, and when there are multiple youtube urls loaded into the playlist it is not possible to differentiate them except by loading every video, which is not convenient.

**Comment by Et0h** [comment]
Syncplay and its protocol is open source so anyone could create a tool to do this if they wanted. We have no plans to add this functionality into Syncplay at present, so I'll be closing this issue soon if no volunteers come forward to work on this project. If someone does want to volunteer to do code such a tool or if someone who is willing to add it to Syncplay wishes to make their case for doing so then they are free to re-open this topic for further discussion.

**Comment by daniel-123** [comment]
Adding a bit to what Et0h said - currently Syncplay doesn't directly interact with URLs at all. Everything about handling them is left to the media players and their libraries. Which in turn tend to support much more than just YouTube - and that's an implementation can of worms I'd prefer to keep closed.

Just adding YouTube API support for retrieving titles and recoding the playlist to display them might not be exceedingly complex, but it would leave the feature very half baked. It would also add to ongoing support burden of entire application for relatively little gain, at least as far as my typical usage goes.

**Comment by Et0h** [comment]
@daniel-123 is correct, Syncplay at present does not interact with URLs. Indeed, it doesn't even interact with the contents of files. It instead relies on the media players, and that means we can't find out much about a file before it is actually loaded into the player.

If your primary focus is syncing YouTube videos then you may wish to look for one of the many web-based solutions which already exist for this particular use case. Syncplay's primary focus is on syncing files rather than streams, and supporting the features you requested would add an additional maintenance burden to Syncplay as well as adding to its complexity.

**Comment by rhetr** [comment]
> Syncplay doesn't directly interact with URLs at all. Everything about handling them is left to the media players and their libraries.

I suspected as much, thanks for clarifying.
