### ISSUE TITLE
Seeking forward issues

### ISSUE THREAD

**Issue by arkangel-dev** [Syncplay/syncplay#452]
**Describe the bug**
I've noticed this issue in rooms with more than 3 clients. When a client seeks to a position ahead of the other clients. It will revert back. However seeking to a position behind the other clients position doesn't result in the same behavior

**To Reproduce**
1. Connect 3 participants to the same server.
2. Load in the same file.
3. Seek forward in one of the clients. The other clients will seek to that point for a few seconds and then revert back to the original position with the reason being "Re winded due to time difference between X". Then the client that was used to seek in the first place will also return to the same, original position with the same reason.

**Expected behavior**
When one client seeks, all clients should seek to the same position and play from there

**Version and platform:**
 - Windows 10 20H2 
 - Syncplay Version 1.6.8

**Additional context**
I've noticed the same behavior from my own client, which leads me to believe that the issue lies in the server

**Comment by daniel-123** [comment]
I haven't seen this issue at all with 4-6 user sessions I typically have.

From really quite long time ago I recall that something like this did happen when at least one of the people watching had their player react extremely slowly due to very slow disk drive they used. I imagine this could also happen if your video is being streamed over network (youtube, personal server, networked drive etc). Is any of those things applicable to any of the participants?

**Comment by arkangel-dev** [comment]
Hey, sorry about the late reply. And no, Im playing a local file and its stored on an SSD. Is it possible that this might happen when the clients are corrected to the same local network?

**Comment by daniel-123** [comment]
Being on the same network should result in lower lateness and hence even lower likelihood of "sticky seeks". Only situation where network could be causing issues is if it's a connection with extremely high jitter like 3g GSM modem on cusp of losing reception.

What video players are you using? Could you test whether the behavior persists if all clients are using mpv? That should help in narrowing down the issue.

**Comment by arkangel-dev** [comment]
I just tested it again with 4 clients. All in their own LANs at different parts of the country. Still facing the same issue. We're all using VLC as the media player. But then again the player does warn about VLC
![image](https://user-images.githubusercontent.com/31138457/128381203-670f67af-c869-475c-a258-0aed258518b3.png)

**Comment by arkangel-dev** [comment]
I guess I'll close this issue then

**Comment by Et0h** [comment]
Yes, I think it's a good guess that it is a VLC issue. Basically, VLC is not very reliable in terms of accurately reporting its position so Syncplay has to make its best guess which is not always current and so sometimes causes problems. We recommend people use mpv because it works better with Syncplay.
