### ISSUE TITLE
Firefox 91.0.1 marks syncplay 1.6.9 as virus

### ISSUE THREAD

**Issue by powerjungle** [Syncplay/syncplay#456]
I'm running Windows 10 and this hasn't happened before, but for whatever reason downloading the installer from the website or Github, marks it as a virus. I have to force Firefox to download the file. When I scan the file using "Microsoft Defender" and "ClamAV" 
it shows no infection. I looked at the commits and nothing looks wrong. This is probably a Firefox problem, but had to notify you guys just in case. When I downloaded the Mumble installer from Github this problem didn't happen.

![Screenshot 2021-08-20 004731](https://user-images.githubusercontent.com/74188410/130153982-b8718e85-bee8-4bf6-8039-4b40b2e6254b.png)

There's no problem when downloading the 1.6.8 installer.

**Comment by Et0h** [comment]
Are you able to submit a false positive report?

**Comment by daniel-123** [comment]
Based on [Virus Total scan](https://www.virustotal.com/gui/url/0c834cdd0d49b5adc4a2a4cf9ed07b9ebb95a72c22d31c9a0e7dffe38c7729a5/details) it's safe, so it seems to be a false positive. I also don't think it directly got onto [Google safe browsing list](https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fgithub.com%2FSyncplay%2Fsyncplay%2Freleases%2Fdownload%2Fv1.6.9%2FSyncplay-1.6.9-Setup.exe&hl=en).

So it's likely that some heuristic is marking it as unsafe. There are at least three factors contributing to it - Syncplay is somewhat niche software, this is a fresh link and the binary is not cryptographically signed.

When testing this on my Windows machine I found that it happens in Firefox, but not in Google Chrome, so that might be a pointer.

**Comment by powerjungle** [comment]
> Are you able to submit a false positive report?
Can't find where to do so.

> and binary is not cryptographically signed
I was thinking this was the cause when it happened.

**Comment by alexfromcanada** [comment]
If you install 1.6.9 Windows Defender also detects syncplayServer.exe as Trojan:Win32/Zpevdo.B

**Comment by afterpartybr** [comment]
> 
> 
> Based on [Virus Total scan](https://www.virustotal.com/gui/url/0c834cdd0d49b5adc4a2a4cf9ed07b9ebb95a72c22d31c9a0e7dffe38c7729a5/details) it's safe, so it seems to be a false positive. I also don't think it directly got onto [Google safe browsing list](https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fgithub.com%2FSyncplay%2Fsyncplay%2Freleases%2Fdownload%2Fv1.6.9%2FSyncplay-1.6.9-Setup.exe&hl=en).
> 
> So it's likely that some heuristic is marking it as unsafe. There are at least three factors contributing to it - Syncplay is somewhat niche software, this is a fresh link and the binary is not cryptographically signed.
> 
> When testing this on my Windows machine I found that it happens in Firefox, but not in Google Chrome, so that might be a pointer.

I downloaded the file and resent it to virustotal and look at this

https://www.virustotal.com/gui/file/5849d909cd786a07ffc88d68400d006303908c5a2469388b00439591bfe68570/detection

And there are some antivirus that after it installs, the virus is detected

**Comment by Et0h** [comment]
I've now reported all of the VirusTotal false positives - see #458
