### ISSUE TITLE
Private server works only in LAN

### ISSUE THREAD

**Issue by 123aezakmi123** [Syncplay/syncplay#467]
**Describe the bug**
Server connection from outside does not work, only LAN. I have already checked windows firewall and tested a few ports.
I have the same problem on server version for Linux (Raspberry).

**Version and platform:**
 - OS: Windows 10
 - Syncplay version and build type: Syncplay 1.6.9 Setup

**Screenshots**

![image](https://user-images.githubusercontent.com/44506505/135927873-de76e3e3-d635-4702-a96c-d736e438c6e0.png)

![image](https://user-images.githubusercontent.com/44506505/135927577-9231f627-da1e-482d-a795-87b854c3fc32.png)

**Comment by Et0h** [comment]
I don't think this is a Syncplay bug as otherwise the public servers would not work. My best guess is that the router needs port forwarding to be properly configured.

I'm assuming people outside your network are having trouble connecting. If you are having problems connecting to your local computer via your public IP address then It is possible that you would need to add an entry to the HOSTS file to route your connection to 127.0.0.1 or 192.168.0.4 or whatever to keep things local.

**Comment by 123aezakmi123** [comment]
@Et0h on my network I have tinyproxy and OpenVPN server that work externally so I don't think there is a problem with port forwarding

For this test I disabled port 8999 on the router, you can see how fast the connection fails ([client log timestamp] 2 seconds vs 21 seconds when the port is open)

![image](https://user-images.githubusercontent.com/44506505/135932648-f164eb91-7f5f-48aa-a440-205b631d634c.png)
![image](https://user-images.githubusercontent.com/44506505/135934420-86574575-5734-48cd-92b1-1f9ce89e202b.png)

I was wondering if there is a log/verbose mode for the server so I can analyze the problem

**Comment by 123aezakmi123** [comment]
Thanks, the test was done with a device on the same network but when I use two different connections it works
