### ISSUE TITLE
Inconsistent beta tag version

### ISSUE THREAD

**Issue by brian6932** [Syncplay/syncplay#524]
**Describe the bug**
So I am writing an auto-updating scoop manifest for this repo which uses the latest bins, and a few things were making it really difficult.
1. The beta tag version is missing a `.`
 It is `1.70-Beta1`, when it should be `1.7.0-Beta1`, it is not following the naming scheme of the other tags and versions.

2.  Much less of an issue, and can be easily worked around, but still one nonetheless, versions across platforms and installation types are using `-` and `_` seemingly interchangeably, ideally they should all use `-` to be consistent with the tags.

**Version and platform:**
 - OS: Windows 10 64-bit

**Additional context**
The 1st issue is really large and actively prevents me from making the manifest, the 2nd much less so.

**Comment by Et0h** [comment]
I've fixed the typo in the label, thanks for letting me know.

I understand your point about the filenames, but if we're going to change from the status quo on this then I think the best approach would be for you to propose the format you think should be followed in a new issue / discussion so that others can provide feedback. I'm not the one who decided all of the filename systems in the first place, so I'm not aware of whether or not they are the way they are due to OS/platform-specific norms or if it was just arbitrary.

**Comment by brian6932** [comment]
yea that's fine, the filename is more of a nitpick I can work around that, the tags was a breaking thing though
