### ISSUE TITLE
Add a chatbox

### ISSUE THREAD

**Issue by jeep70** [Syncplay/syncplay#54]
That sounds like a pretty convenient feature to me. Perhaps combine it with the notifications section on the left.

**Comment by Et0h** [comment]
Using Syncplay as a chat medium is certainly something we have considered in the past. One of the reasons it has not already been implemented is because chat facilities have the potential to be abused, and we didn't want to spend all our time working on moderation tools for it when established chat solutions already existed.

Last time I thought about it I saw two potential ways around that issue:

1. Have Syncplay-based chat enabled on a server-by-server basis, so if you are running a server with friends who won't abuse the feature then you can enable it, but we wouldn't have it enabled on the public server and so don't have to worry about moderation; and
2. Build an IRC client into Syncplay, so then it can all take place on someone else's server which already has established forms of oversight.

It'd be useful to hear what people's thoughts are on chat functionality, and on how to manage its potential for abuse.

**Comment by iansampaio** [comment]
I like the idea of having a chat. Perhaps it'd be less intrusive if it was integrated to the player, and shown along with the video timeline like Soundcloud does:

![screenshot 2015-03-13 12 55 11](https://cloud.githubusercontent.com/assets/439176/6637942/ab1fbbf8-c980-11e4-9744-5e07b29a632d.png)

**Comment by Et0h** [comment]
That's an interesting idea, but Syncplay can't really integrate stuff into the media player like that. Adding such functionality into every player Syncplay supports would be a nightmare, let alone maintaining such functionality if it has to be a branch because the people who made the player didn't want it complicating their code. If it were to be added to the Syncplay window it'd be a lot work for something which people mostly wouldn't see.

That said, if Syncplay allowed logging of what comments were made during a Syncplay session, what file was being played at the time, and the file position at the time, then someone could create a utility to generate such a representation of the video after-the-fact.

Logging with context would also be useful for people wanting to blog their views about shows they are watching (especially if chats could be logged to a file). It would be fun if there was a way to automatically have screencaps of when people made the comment, maybe including the comment itself, but again that might be better off as a separate utility that parses the chat log then the video rather than something within Syncplay. Arguably that's fairly specialist so not a top priority, but it would be pretty neat.

**Comment by abhsag24** [comment]
how about private chatboxes instead of public ones? where a person could message a specific user, and based on that message the user could chose weather to receive more messages from that specific person

**Comment by Et0h** [comment]
See https://github.com/Syncplay/syncplay/pull/90 and chat branch which has an alpha of this feature.
