### ISSUE TITLE
SSL connection abruptly cut in certain countries

### ISSUE THREAD

**Issue by Someone7un7** [Syncplay/syncplay#553]
I can't connect to any of syncplay servers
What do I do?????

**Comment by Et0h** [comment]
What operating system are you using? It is working fine for me using Windows 10, but https://github.com/Syncplay/syncplay/issues/554 reports someone having trouble connecting on Windows 11 due to a certificate error.

**Comment by Et0h** [comment]
Please run Syncplay with the --debug command line switch and let me know of anything potentially relevant which gets put into the syncplay.log or .Syncplay.log file in %APPDATA%.

**Comment by Et0h** [comment]
Also do you get any errors when you visit the https://syncplay.pl/ website in your browser?

**Comment by Someone7un7** [comment]
no no I can simply visit syncplay.pl website without any error I mean I don't need to change my IP or something , and that --debug command which you said didn't do anything , by the way , I'm from Iran

**Comment by Et0h** [comment]
This might be the same issue as https://github.com/Syncplay/syncplay/issues/554 and so might have the same solution.

Could you please try again with the build from https://github.com/Syncplay/syncplay/actions/runs/3235129755 and let me know if that fixes it.

**Comment by Someone7un7** [comment]
> This might be the same issue as #554 and so might have the same solution.
> 
> Could you please try again with the build from https://github.com/Syncplay/syncplay/actions/runs/3235129755 and let me know if that fixes it.

I tried it and it didn't work , these are the notifications that are shown:

[17:30:02] Attempting to connect to syncplay.pl:21
[17:30:03] Attempting secure connection
[17:30:03] Successfully reached syncplay.pl (151.80.32.178)
[17:30:03] Connection with server lost, attempting to reconnect
[17:30:03] Attempting secure connection

I don't know why it doesn't work ☹
It was really a cool app

by the way, I have windows 10
tried everything buddy
I have no idea

maybe it is because of the internet problems that we have in Iran these days , but I don't think so because my friends can use syncplay , they can connect

**Comment by Et0h** [comment]
@Someone7un7: With https://github.com/Syncplay/syncplay/pull/564 I've done some changes so that if an initial attempt fails for a TLS-related reason then it should now always try again using a plaintext connection but warn the user

Please try it out and let me know if you ca now use Syncplay: https://github.com/Syncplay/syncplay/actions/runs/3401531009 (scroll to the artifacts at the bottom and choose Syncplay-1.7.0-Setup.exe or Syncplay_1.7.0_Portable).

If that doesn't work please try to run it in --debug mode and let me know if it gives any reasons.

**Comment by Et0h** [comment]
@Someone7un7: With https://github.com/Syncplay/syncplay/pull/565 I've made it give more explicit error messages when the connection is lost.

Please try it out and let me know what error it gives: https://github.com/Syncplay/syncplay/actions/runs/3402038853 (scroll to the artifacts at the bottom and choose Syncplay-1.7.0-Setup.exe or Syncplay_1.7.0_Portable).

**Comment by Someone7un7** [comment]
Nothing worked , I'm using VPN

**Comment by Et0h** [comment]
There is some discussion of how to modify Syncplay code to run through a proxy at https://github.com/Syncplay/syncplay/issues/346 but generally speaking Syncplay was only ever designed to connect directly to the server. As such this seems less like a bug and more like a feature request.

**Comment by daniel-123** [comment]
@Someone7un7 

Is the connection working fine without VPN?

Syncplay does use somewhat less typical port, so it's hard to tell whether VPN would interfere with it or not.

**Comment by Gieted** [comment]
I'm experiencing the same problem (started to happen just recently). I'm not using any VPN. 
![obraz](https://user-images.githubusercontent.com/35242233/205463313-1628e8b0-0055-4bde-ae3c-25acea766054.png)

**Comment by Someone7un7** [comment]
> @Someone7un7
> 
> Is the connection working fine without VPN?
> 
> Syncplay does use somewhat less typical port, so it's hard to tell whether VPN would interfere with it or not.

When I use the app without VPN it doesn't work so I have to use VPN to connect to the servers . It works only with VPN and when i use VPN it works perfectly

**Comment by Someone7un7** [comment]
> I'm experiencing the same problem (started to happen just recently). I'm not using any VPN. ![obraz](https://user-images.githubusercontent.com/35242233/205463313-1628e8b0-0055-4bde-ae3c-25acea766054.png)

this is exactly what I experience when I try to connect to the app servers without VPN

**Comment by albertosottile** [comment]
@Someone7un7 Can you try again with the build included here https://github.com/Syncplay/syncplay/actions/runs/3402038853 ? Please start Syncplay with the  `--debug` argument as that provides a more detailed error message. I would appreciate if you could try with and without VPN, and report here the printed debug messages. Thanks.

**Comment by Someone7un7** [comment]
> @Someone7un7 Can you try again with the build included here https://github.com/Syncplay/syncplay/actions/runs/3402038853 ? Please start Syncplay with the `--debug` argument as that provides a more detailed error message. I would appreciate if you could try with and without VPN, and report here the printed debug messages. Thanks.

sorry for being late , I've just seen your comment and did what you asked me to do and it is just like before , it only works with VPN

**Comment by Someone7un7** [comment]
Problem is solved , now everything is ok and I can use Syncplay without vpn

**Comment by Et0h** [comment]
It's good to hear that the problem is solved, although I'm not sure quite sure what changed.

**Comment by Talkbullet** [comment]
Hi, I also got the same problem while using Syncplay.
Every 3-5 minutes the connection to the server disappears, although everything is fine with the Internet.
Is there any way to fix this?

Windows 11, Syncplay v1.7.0 development, no VPN
If you need to send any info, please let me know.

**Comment by Talkbullet** [comment]
1. Lithuania
2. Using provider's router
3. Sometimes wi-fi, but most of the time with cable
4. https://www.waveform.com/tools/bufferbloat?test-id=98d05bbe-5f20-439a-be32-17a572b2d686

Don't know how to start my own server, so i can't check it

**Comment by Talkbullet** [comment]
@Et0h

Hi again, after the update it started giving errors like this.
Any ideas what it could mean?
Repeats every 5 or 15 minutes.
![image](https://user-images.githubusercontent.com/106967705/230672280-a4fb6ea2-d97b-4985-a75b-878375619e6c.png)

**Comment by Et0h** [comment]
@Talkbullet When it disconnects does it successfully reconnect quickly?

Syncplay's client and server both talk regularly to stay in sync and both use a timeout threshold of 12.5 seconds. This means that if 12.5 seconds has passed since the last relevant update they assume that the connection has failed and reconnect. What I don't know is what the timeout is from the TCP/TLS protocol which Syncplay servers and clients use - I assume it is whatever the default is for Endpoints (or is it something set at an OS level?).

Syncplay's timeouts might be more strict than some systems, but it prevents situations where you can be disconnected for a long time and nobody realises it because the server and clients think the connection is still alive when it is not (which I seem to recall being an issue with Mumble, at least in the past). It might also be the case that other systems do reconnecting silently so you don't even know you were disconnected and reconnected.

Disconnection could potentially happen more frequently if you either have a flakey connection to your ISP, or if the connection between the ISP and Syncplay's public servers (which are hosted in France) is flakey.

A separate issue is if the server has been on too long and needs to be restarted to work reliably again. In my understanding it has not been long since the server was last restarted, and it'd start effecting a lot more people. However, you can always try a different port (I think syncplay.pl:8996) to see if it helps.

Something else you could try is to use a third-party client such as https://syncplay.net/ and see if the issue still occurs.

Finally, you could try running you own server (or getting a friend to do so) following the instructions at https://syncplay.pl/guide/server/

**Comment by soredake** [comment]
![изображение](https://github.com/Syncplay/syncplay/assets/5204968/7ffc21a7-166b-4178-a637-87a4af68298d)

Meh, syncplay worked fine for some years, now i'm getting this on 8999 port.

**Comment by Et0h** [comment]
Thanks for reporting this issue. The port 8999 instance on the Syncplay server has been restarted and so should be working fine now. As far as I can tell the other instances were unaffected.

**Comment by soredake** [comment]
@Et0h can you make servers auto-restart after some time? This will probably help with this issue.

**Comment by soredake** [comment]
8999 / 8998 both unusable for me without vpn, again, this issue needs a solution.

**Comment by Et0h** [comment]
The server has been restarted and has now been set to automatically restart on the first and third Monday of the month at 9am France time. We have also adjusted the power profile to more performance oriented one. Let us know if you have any future issues.

**Comment by soredake** [comment]
![image](https://github.com/Syncplay/syncplay/assets/5204968/14752e6b-ebe8-4933-9a75-cb739528b158)

Unfortunately it seems that restarting server is not enough to fix this.

**Comment by Et0h** [comment]
The problem is therefore probably not with Syncplay but somewhere else on the route from your PC to Syncplay, e.g. your ISP.

**Comment by soredake** [comment]
> The problem is therefore probably not with Syncplay but somewhere else on the route from your PC to the Syncplay public servers, e.g. your ISP.

It happens to me and two of my friends, we all live in different countries.

>Your best option might be to run your own Syncplay server.

I'll try this.

**Comment by soredake** [comment]
My self-hosted syncplay instance started giving similar (`clean` instead of `non-clean`) problems after a month without reboot, after rebooting frequent disconnects are stopped for now.
