### ISSUE TITLE
Pause or reset to start on reaching end of file

### ISSUE THREAD

**Issue by wiiaboo** [Syncplay/syncplay#57]
Not really a bug, but an annoying feature on Syncplay keeps the same position even when a file ends or changes to the next on the playlist.
Happens with mpv and mpc-hc.
When the next file has a smaller duration it then instantly changes to the next until a file has higher duration and it finally stops.

**Comment by Et0h** [comment]
I agree it is annoying. However, it is less annoying than if it didn't do it, because then if someone changes file during playback (e.g. because they had the wrong file open) it would reset everyone. This is also why it would mess up playlists, as the first person to get to the end of the file would prevent others from getting to the end of the file, and it is impossible for Syncplay to reliably determine whether you are near the end of the file (because not all APIs correctly report media duration).

If you shift+drag the file into Syncplay it is supposed to set position to 0, but it might not be reliable (programmers are free to try and improve the reliability of that functionality, it isn't something I use myself so it hasn't had full testing). Because of how Syncplay works it just can't be compatible with player-based playlists, but there are plans for a Syncplay-based playlist in the future - see https://github.com/Syncplay/syncplay/issues/40 for more details and to discuss these matters.
