### ISSUE TITLE
VLC time shifted a bit after pause

### ISSUE THREAD

**Issue by Freewolny** [Syncplay/syncplay#58]
When I pause the video in VLC, it changes its position a little bit - not only on other people's players, but on mine, too. It's annoying especially when I want to pause video to have time to read long, quickly changing subtitles.

**Comment by Et0h** [comment]
Thank you for reporting this matter. As regulars of our IRC channel should be aware, this is one of two VLC-related mis-seeking issues that is currently being investigated (the other being an erroneous 0/1 sec seek during playback). As a workaround, it is possible that changing SYNC_ON_PAUSE to False in constants.py will fix the issue (and/or you could try using mpv).

**Comment by Et0h** [comment]
Hopefully these issues are fully fixed by https://github.com/Syncplay/syncplay/commit/0a94070967397c6017c2f0bdb4abf925d5da7a07 and https://github.com/Syncplay/syncplay/commit/a3c38300279a59cf43cfc8103380c26b0f014d47 - let me know if they persistent. Build which incorporates these commits is available from http://syncplay.pl/Syncplay_1.3.0_Beta_Setup_[2015_03_27].exe - note: position may be slightly off for other users when you pause as it seeks to position rather than frame, but will mean it won't move the person who seeked.

**Comment by Et0h** [comment]
Syncplay 1.3.0 Beta 3d is now available from http://syncplay.pl/syncplay-1-3-0-beta-3/ - does this address your issue?

**Comment by Freewolny** [comment]
Oh, I'm sorry for not having responded to your previous e-mail. These
issues were fixed by 0a94070
<https://github.com/Syncplay/syncplay/commit/0a94070967397c6017c2f0bdb4abf925d5da7a07>
 and a3c3830
<https://github.com/Syncplay/syncplay/commit/a3c38300279a59cf43cfc8103380c26b0f014d47>.
Thank you very much. :-)

wt., 21.04.2015 o 13:53 użytkownik Etoh <notifications@github.com> napisał:

**Comment by Et0h** [comment]
Excellent, glad to hear the issues have been resolved :)
