### ISSUE TITLE
`Syncplay-1.7.0-Setup.exe` false positives on virustotal

### ISSUE THREAD

**Issue by soredake** [Syncplay/syncplay#599]
**Describe the bug**
`12 security vendors and no sandboxes flagged this file as malicious` on virustotal https://www.virustotal.com/gui/file/0afb93a1baed3d9b90580b297a7f94ec46183463dda9171b1434c76141e0620c

**To Reproduce**
1. `Syncplay-1.7.0-Setup.exe` to virustotal.
2. It is marked as trojan.

**Expected behavior**
Not being marked as trojan by virustotal (which stalls updating version in chocolatey repo https://community.chocolatey.org/packages/syncplay/1.7.0)

**Screenshots**
![image](https://user-images.githubusercontent.com/5204968/229548305-a3c80ec6-2b03-4ade-82d9-84b9822d6065.png)

**Version and platform:**
 - OS: Windows 11 Pro
 - Syncplay version and build type: syncplay 1.7.0
 - Media player and version:

**Additional context**

**Comment by Et0h** [comment]
I have just made 'false positive' reports to all the vendors, so now it's just a waiting game. Usually they update their definitions within a few days to remove the false positive, but it differs from vendor to vendor.

**Comment by Et0h** [comment]
Two down...

**Fortinet response:**
```
Hi,

Thanks for raising this issue, we have noted a False Positive detection on a file named "Syncplay-1.7.0-Setup.exe" with MD5:4c920bfaeb5ed0868b522ed921b48c89. 
The signature "W32/PossibleThreat" will be disabled and changes will be reflected in the next Virus Signature update. We sincerely regret any inconvenience this might have caused you.

If you have any further concerns, please do send us a mail and we will immediately assist you.

Best Regards,
AV Lab - Gabriel
```

**Avast response:**
```
Hello,

Thank you for reporting this false positive.

We have now cleared its reputation in our database based on the findings and removed the detection. This change may take up to 24 hours to take full effect. Please accept our apology for the inconvenience caused.

If the detection persists after 24 hours, update the virus database in Avast anti-virus and reply to this email with the attached files:
1.Take a screenshot of the Avast detection dialog (Threat Secured pop-up with See details - displayed at the bottom).
2.Take a screenshot of the Avast virus database (open Avast antivirus and go to Menu > About).
We hope you have a nice day and stay safe online.

Lukas
Avast Malware Analysis Team
```

**Comment by Et0h** [comment]
**Response from SecureAge:**
`Hello, Your submission (20230405-155609349800/Syncplay-1.7.0-Setup-FalsePositive.zip) has been successfully processed. Your false detection(s) will be cleared within the next 72 hours; please notify us if that is not the case. For APEX results on VirusTotal, false detections may take additional time to clear. You may need to reanalyse files in order to get the updated detection result. Thank you for your report. SecureAPlus Admin`

**Responses from Malwarebytes forum:**
`I can't reproduce detection when I scan the file locally. So this means that this has been resolved/whitelisted already, so any user running Malwarebytes won't get a detection for this file. Both are clear on VT as well.`
