### ISSUE TITLE
"This client does not support TLS"

### ISSUE THREAD

**Issue by DemonicSavage** [Syncplay/syncplay#601]
**Describe the bug**
Syncplay used to support TLS, but it seems broken.

**To Reproduce**
1. Connect to a TLS-enabled server

**Expected behavior**
TLS should be supported

**Screenshots**
![Screenshot_20230414_005808](https://user-images.githubusercontent.com/1365501/231938099-67ecb6c8-0410-48b3-8aef-c819a680bae7.png)

**Version and platform:**
 - OS: Arch Linux
 - Syncplay version and build type: Syncplay 1.7.0 (with https://github.com/Syncplay/syncplay/commit/b62b038cdf58c54205987dfc52ebf228505ad03b applied to fix an unrelated issue)
 - Media player and version:  mpv latest

**Additional context**

**Comment by Et0h** [comment]
You could try --debug to see if that helps you narrow down the problem.

I just did some testing of the official 1.7.0 builds, and TLS worked fine for both the Windows executable on Windows 10 and the AppImage on Ubuntu 22.0.4.1 LTS.

If you are trying to connect to localhost then TLS might not work because the details don't match what is expected as it is connected via a loopback, but in that case there is no real incentive to use TLS because it would be connected  via a loopback rather than over the Internet.

Potentially related bug report: https://bugs.archlinux.org/task/78153

**Comment by DemonicSavage** [comment]
Somehow I didn't have the `pem` Python module installed. Installing it fixed this.

**Comment by zeroeightysix** [comment]
Shouldn't this dependency be listed on https://syncplay.pl/guide/install/ ?

Just had to figure out why syncplay wouldn't connect through this (closed!) issue, after pulling my hair out figuring out why it wouldn't work despite me having all the listed requirements.

**Comment by Et0h** [comment]
Good point. I've now added pem to https://syncplay.pl/guide/install/
