### ISSUE TITLE
Mpv with thumbfast script

### ISSUE THREAD

**Issue by ymn236** [Syncplay/syncplay#622]
**Describe the bug**
I'm using the thumbfast script with mpv, it's working fine but it bugs only when using Syncplay.

**To Reproduce**
1. Install thumbfast script with the default osc.lua
2. Open Syncplay with mpv
3. Rover on the timeline

**Expected behavior**
![1](https://github.com/Syncplay/syncplay/assets/139700546/e47f6b1d-3cf5-478d-96bf-d072baa775e1)

**Bug**
![2](https://github.com/Syncplay/syncplay/assets/139700546/b90c7066-7109-48ef-a7b6-225a598e0697)

**Version and platform:**
 - OS: Windows 10 64-bit
 - Syncplay version and build type: Syncplay 1.7.0
 - Media player and version:  mpv 0.35.1 v3

**Additional context**
Script link: https://github.com/po5/thumbfast

**Comment by Et0h** [comment]
I can confirm that this is how thumbfast behave, but I have not been able to figure out why.

You could try making an issue on the thumbfast GitHub as they might be able to figure it out. For example, it could relate to the mpv default path folder or in the program calling it being or being administrator.

**Comment by ymn236** [comment]
Yeah, they solved it and it's working fine now. Here's the link if you want to fix it on Syncplay, if possible.
https://github.com/po5/thumbfast/issues/100#issuecomment-1652066750

**Comment by Et0h** [comment]
Excellent work! Based on this thread I've been able to determine that the issue was that Syncplay in effect ran mpv with --osd-align-y=bottom but thumbfast was only designed to accommodate --osd-align-y=top. I can confirm that the recent commit to thumbfast fixes the issue.

**Longer explanation:**

With the additional information I've tracked down the source of the issue to the following line in Syncplay's code:
https://github.com/Syncplay/syncplay/blob/884d79bed3d067d7025a53eb23bc7c7828134ab8/syncplay/players/mpv.py#L475

The reason this line exists is that Syncplay needs mpv OSD notifications such as when you change subtitle tracks to appear at the bottom of the screen so it doesn't overlap with Syncplay's own OSD code.

The fact that the change to thumbfast to add elem_ass:an(7) to osc.lua resolves their problem without undoing Syncplay's fix means I do not need to investigate whether there is a way to move the OSD notifications to the bottom without setting osd-align-y to bottom.

Given that setting (a) osd-align-y is documented mpv behaviour, (b) Syncplay uses this behaviour for a good reason, and (c) there is a viable workaround that thumbfast has been implemented, I consider this matter resolved.
