### ISSUE TITLE
Dragging and Dropping Files Isn't Working

### ISSUE THREAD

**Issue by Shuukaa** [Syncplay/syncplay#623]
**Describe the bug**
Can't seem to be able to drag and drop files into Syncplay on Windows 11. Is this a known issue? Right clicking and adding file to bottom of playlist works, but dragging and dropping doesn't.

**To Reproduce**
1. Open Syncplay room
2. Drag file from different folder on top of Syncplay
3. Gets red warning symbol
4. Nothing is dropped

**Expected behavior**
I expected that I would be able to drop it like normal after re-installing windows.

**Screenshots**
![image](https://github.com/Syncplay/syncplay/assets/69614231/d535abee-c7cd-4e70-a87a-b2118c58562d)

**Version and platform:**
 - OS: Windows 11 64-bit
 - Syncplay version and build type: Syncplay 1.6.5 from Installer
 - Media player and version:  MPV x86 64bit 20200322

**Additional context**
The reason why I am not up to date in versions is because the program never seems to open with the newest syncplay version, and it seems some of the newer versions of mpv weren't compatible with my current version of Syncplay.
You can view the error log I have [here]https://pastebin.com/WCMfG8zf(url).

**Comment by Et0h** [comment]
I experience that issue when running Syncplay as Administrator on Windows 11. I assume the issue is related to https://forum.qt.io/topic/131155/qt-applications-cannot-drag-and-drop-files-when-running-under-windows-with-administrator-rights/13 which makes it a QT bug rather than a Syncplay bug. You should still be able to right click and select add files, but I appreciate that dragging and dropping is easier.

Your paste bin expired, but I just tried Syncplay 1.7.0 with  64bit-v3 (mpv-x86_64-v3-20230723-git-ca4192e.7z) available from https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/ and it seems to work fine. I've also tried it with mpv.net v6.0.3.2-beta available from https://github.com/mpvnet-player/mpv.net/releases and that also seems to work fine on Windows 11.
