### ISSUE TITLE
Possible malware in Syncplay_1.7.0_Portable.zip

### ISSUE THREAD

**Issue by RioNight** [Syncplay/syncplay#640]
**Describe the bug**
When I try to install Syncplay on Windows 11 with scoop, the hash check fails, and Windows Defender reports some malware (see the image below). The same malware is reported when Syncplay_1.7.0_Portable.zip is manually downloaded from the GitHub releases.

**To Reproduce**
1. Run `scoop install syncplay` on Windows 11.
Or:
2. Download Syncplay_1.7.0_Portable.zip from the GitHub releases.

**Expected behavior**
Syncplay should have been downloaded properly.

**Screenshots**
![image](https://github.com/Syncplay/syncplay/assets/58403689/14ef2c33-924c-409a-9ffa-9c4950f0f833)
![image](https://github.com/Syncplay/syncplay/assets/58403689/c2781007-9ddf-4f9b-8189-fe5a242e98a4)

**Version and platform:**
Windows 11 and scoop.

**Additional context**
The scoop Syncplay manifest:
https://github.com/ScoopInstaller/Extras/blob/master/bucket/syncplay.json

**Comment by Et0h** [comment]
The log you posted indicates that the reason it failed the hash check is because the file could not be found, presumably because Windows 11 quarantined it due to a false positive.

Report the false positive via https://www.microsoft.com/en-us/wdsi/filesubmission and in a few days they should confirm it was a false positive and give you instructions on updating your engine to a more recent definition where the file is no longer flagged.

**Comment by Et0h** [comment]
I've submitted the file as a false positive. Let's hope Microsoft listens!
