### ISSUE TITLE
MPV interface is stretched out and button are messed up when you use `window-maximized=yes` until you go to full screen

### ISSUE THREAD

**Issue by soredake** [Syncplay/syncplay#678]
**Describe the bug**
MPV interface is stretched out and button are messed up when you use `window-maximized=yes` until you go to full screen

**To Reproduce**
1. Install syncplay.
2. Install mpv-git from scoop.
4. Setup path to mpv-git in syncplay.
5. `--no-config --window-maximized=yes` set this as player arguments.
6. Load some file, I used 4k movie.
7. Interface is stretched and button are messed up, for example, pressing play will actually trigger playlist change to previous item.

**Expected behavior**
No such problem observed with mpv.net

**Screenshots**
![Screenshot 2024-04-30 135615](https://github.com/Syncplay/syncplay/assets/5204968/d11e4d40-019f-487a-aea9-0f92e3fce584)

**Version and platform:**
 - OS: Windows 11 Pro
 - Syncplay version and build type: Syncplay 1.7.2
 - Media player and version: mpv v0.38.0-63-gb364e4a6

**Additional context**

**Comment by Et0h** [comment]
I don't use scoop so I tried with https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20240421-git-b364e4a.7z/download with Syncplay 1.7.3 and on my set-up it the text in the top-left is a bit small for like half a second then corrects itself.

It is possible that the issue only sticks around on a computer that is running faster and/or slower than my computer which causes something to happen too soon or too late, maybe relating to the timing/sequencing of `mp.command('print-text "<get_syncplayintf_options>"')`  in syncplayintf.lua which triggers `self._sendMpvOptions()` in mpv.py. However, since I can't reproduce unfortunately I am not in a position to work on a fix.

**Comment by soredake** [comment]
This stretching issue can be fixed with `auto-window-resize=no`
