### ISSUE TITLE
Sometimes before changing playlist item to next, time is set to 00:00:00

### ISSUE THREAD

**Issue by soredake** [Syncplay/syncplay#683]
**Describe the bug**
Sometimes before changing playlist item to next, time is set to 00:00:00, which is breaks trakt-scrobbler because stop event is not happening on >=80% due to changed time 

**To Reproduce**
1. Add multiple playlist items
2. Play it to the end
3. Sometimes before changing playlist item to next, time is set to 00:00:00
4. trakt-scrobbler will not see stop event, due time changeed to 00:00:00

**Expected behavior**
This should not happen ideally to not break trakt-scrobbler.

**Screenshots**
Not really needed.

**Version and platform:**
 - OS: Windows 11 Pro
 - Syncplay version and build type: Syncplay 1.7.3
 - Media player and version:  mpv-git

**Additional context**
https://github.com/iamkroot/trakt-scrobbler/issues/202#issuecomment-2016771436

**Comment by Et0h** [comment]
It'd be useful to see --debug logs showing the moment when Syncplay sends a command to set the position to 0 prematurely. 

This is because what is stated in the notification window might not reflect what is happening under the hood, and it is what is happening in the communication with mpv which is important to your issue.

Specifically I am interested in if the problem that it resets to 0:00 before changing the file or that it pauses just before getting to EOF.

**Comment by soredake** [comment]
> It'd be useful to see Syncplay --debug logs showing the moment when Syncplay sends a command to mpv to set the position to 0 prematurely.

I've added `--debug` argument to syncplay, will send logs when this will happen again.

**Comment by soredake** [comment]
@Et0h here is the logs
[syncplay_beginning_rewind.log](https://github.com/user-attachments/files/15787236/syncplay_beginning_rewind.log)

**Comment by soredake** [comment]
> or was it auto-advancement

Yes, it is auto-advancement.



> Also, any idea why there was such a 7 second gap between the seek at 14:44:47 and the change of file at 14:44:54?

Maybe we loaded a youtube video, which takes some time to load.

**Comment by Et0h** [comment]
> > or was it auto-advancement
> 
> Yes, it is auto-advancement.
> 
> > Also, any idea why there was such a 7 second gap between the seek at 14:44:47 and the change of file at 14:44:54?
> 
> Maybe we loaded a youtube video, which takes some time to load.

I just checked and it was a local mkv file.

When at 14:44:47 it says that position was set to 0 by a specific user, was that the user whose log this is or a different user?

On this person's computer, do seeks take sometimes take a long time?

**Comment by soredake** [comment]
> When at 14:44:47 it says that position was set to 0 by a specific user, was that the user whose log this is or a different user?

None of us set position manually.

>do seeks take sometimes take a long time?

Loading files are definitely slower on my friend's side as he uses mpv.net which takes 1–3 seconds more to load files, at least on my machine, I'll advise him to switch to plain mpv.

**Comment by Et0h** [comment]
I think the issue might be that the way it works is that when you advance the first thing the client does is send a message saying the position should be 0 and the next thing it does it advance the playlist:

https://github.com/Syncplay/syncplay/blob/fix_missing_rewind/syncplay/client.py#L2074-L2076

https://github.com/Syncplay/syncplay/blob/fix_missing_rewind/syncplay/client.py#L256-L260

I tried just deleting this code but then it seemed to cause other problems with advancement.

Half measures seems to fix one problem and then create another. As such, I'm starting to think that to properly fix this issue and #618 the entire way that Syncplay handles playlist item changing and advancement needs to be recoded from scratch so that clients basically treat changing playlist item and resetting to zero are the same thing (except when you join a room) and so that it doesn't affect the position until it has actually loaded the file, but that would take quite a bit of time to test (especially with backwards compatibility and inter-client compatibility). Such a rework might require server changes, but it might be possible to make clever use of the existing protocol. I have no idea when I'd have time for such an undertaking, and its all complicated by the fact that in my own use of Syncplay the advancement system seems to generally work fine, which makes it even harder for me to test whether the fixes actually fix stuff or whether it might actually make it work.

**Comment by Et0h** [comment]
I've made a lot of changes to how playlist advancement and switching works on my test branch. Please let me know if this fixes your issue and/or if it introduces new bugs.

https://github.com/Syncplay/syncplay/actions/runs/9612802702

**Comment by soredake** [comment]
Testing this for 4 days, so far this problem is gone, will continue testing.

**Comment by soredake** [comment]
Unfortunately, this problem is not yet fully gone, it still happens, thought not as frequent as before. Will post logs later.

**Comment by Et0h** [comment]
The test branch has now been updated to also merge in other unrelated changes to Syncplay. See:
* https://github.com/Syncplay/syncplay/tree/fix_missing_rewind
* https://github.com/Syncplay/syncplay/actions/runs/11112391724

**Comment by soredake** [comment]
@Et0h with this build and month of testing, I don't experience this problem anymore.

**Comment by Et0h** [comment]
@soredake Thank you for your testing. PR #698 has now been merged into the main branch.
