### ISSUE TITLE
GUI Does not appear on Arch

### ISSUE THREAD

**Issue by LeKite** [Syncplay/syncplay#688]
**Version and platform:**
 - OS: Arch Linux
 - Syncplay version and build type: latest from arch repo
 - Media player and version:  latest mpv from arch repo

**Additional info**
I've read here and there that it is an issue with python.. but it should be fixed already. Syncplay worked fine for months for me, some day probably due to pyside2 it stopped opening the GUI. What should I do? I expected it to work since I have latest syncplay version...
I've already tried removing it and reinstalling with no success.

**Comment by daniel-123** [comment]
I'm looking at [package from official Arch repo](https://archlinux.org/packages/extra/any/syncplay/) - this is what you installed? 

I would have three main questions:

- Does it say anything in the standard output when you try to run it from command line?
- Does it work normally with `--no-gui` switch? This will tell you whether there is something broken with the GUI and associated libraries or if it's something more fundamental.
- Do you have pyside6 installed along with other optional dependencies? Not sure how those are treated by default on Arch.

**Comment by LeKite** [comment]
> I'm looking at [package from official Arch repo](https://archlinux.org/packages/extra/any/syncplay/) - this is what you installed? 
> 
> 
> 
> I would have three main questions:
> 
> 
> 
> - Does it say anything in the standard output when you try to run it from command line?
> 
> - Does it work normally with `--no-gui` switch? This will tell you whether there is something broken with the GUI and associated libraries or if it's something more fundamental.
> 
> - Do you have pyside6 installed along with other optional dependencies? Not sure how those are treated by default on Arch.

Actually, thanks for answering, I realized I missed pyside6. Why doesn't it get shipped with dependencies?

**Comment by daniel-123** [comment]
> Why doesn't it get shipped with dependencies?

That's a question purely to the maintainer of the Arch package - they have decided that it's an optional dependency. Packages that are in repositories of various distributions aren't really controlled directly by Syncplay devs.

From Syncplay side - technically GUI is optional, even though it's basically the default.

As a reference - the on Debian and its derivatives, the Syncplay package does straight up require GUI components. Though given respective philosophies of Debian and Arch - their respective approaches to Syncplay dependencies make perfect sense IMHO.

**Comment by FichteFoll** [comment]
[`pyside6`](https://archlinux.org/packages/extra/x86_64/pyside6/) itself has *several* dependencies, notably qt6, which you wouldn't need to install if you were just interested in using syncplay as a standalone without a GUI. Thus, having this as an optional dependency certainly makes sense.

This wasn't a recent change, however, since pyside2 has also been an optional dependency [2 years ago](https://gitlab.archlinux.org/archlinux/packaging/packages/syncplay/-/commit/3a8da91d6d281050f8d82ca9c04b0e550c6b2af9#9b9baac1eb9b72790eef5540a1685306fc43fd6c_0_16). Maybe something else on your system required it and thus the switch to pyside6 (still an optdep) caused the problem since it's not required by something else anymore (because I ran into it as well).

**Comment by sarahzrf** [comment]
I had this same issue just now and I discovered by attempting to launch syncplay from a terminal that the failure to open a GUI is in fact a segfault. That seems like a bug to me.

**Comment by daniel-123** [comment]
@sarahzrf segfault is absolutely not expected behavior.

Syncplay *does* try to print a message to stdout that it cannot find required libraries. Seeing a segfault instead means you are experiencing some entirely different problem. I've just checked, and this warning does work properly on my Debian system. If you are still seeing this problem, it will benefit from creating an entirely separate new issue as it's different thing.

Displaying some kind of dialog window when failing to import GUI libraries is an option which suffers from a chicken-and-egg problem - there is no GUI libraries present to display it to begin with. I do not know of any good ways of achieving this, though you can suggest some in the discussions.

All of this circles back to defaults set by maintainers of the package dependencies on Arch and should be brought up with them.
