### ISSUE TITLE
Syncplay for mobile

### ISSUE THREAD

**Issue by miahj13** [Syncplay/syncplay#98]
Hi,

What is the likelihood of having Syncplay developed for Android and iOS?

Thanks,
miahj13

**Comment by Et0h** [comment]
There's no easy way to port it, so I reckon that it is quite unlikely unless the developers of an existing and established open source mobile media player project decide to add Syncplay support to their media player. Feel free to try to convince them of the value of such an endeavour as it'd be pretty neat.

**Comment by Et0h** [comment]
A third party has now produced an Android Syncplay app called 'SyncPlayer' available from https://play.google.com/store/apps/details?id=io.github.powerinside.syncplay&hl=en but as it is not released by us it is a 'use it at your own risk' type deal.

**Comment by PowerInside** [comment]
I'm the dev behind 'Syncplayer' app for Android. It's far from perfect, but I've [open sourced it](https://github.com/PowerInside/syncplayer/) so pull requests are welcome and I also plan to work on it when I get more free time. You can also find it on [f-droid](https://f-droid.org/packages/io.github.powerinside.syncplay/).

**Comment by rvalitov** [comment]
It would be great if syncplay could work on mobile platforms. Today most people use iPhones and iPads for entertainment and movies, not computers.

**Comment by sepsol** [comment]
Any news on an iOS app that supports Syncplay like the Android example does?

**Comment by yuroyami** [comment]
@sepsol I am working on an iOS counterpart, but I will not be able to host it on the Apple Store. Other deployment methods might be required.

**Comment by sepsol** [comment]
Kudos to you, I am looking forward to that! Do you have any ETA for when it's gonna be available? Also, why have you decided to not go with Apple Store, and how is the user expected to install your app on their device when it comes out?

**Comment by yuroyami** [comment]
@sepsol, I want to prioritize the development of the Android version since it still lacks numerous features. Consequently, progress on the iOS counterpart will be slow. I currently have several other projects that require my attention, which limits my ability to focus on open-source endeavors. If I were to provide an estimate, I would say that a "very rough" ETA would be a few months away, at the very least.

Regarding the inability to host the app on the Apple Store, it primarily stems from Apple's requirement of a hundred-dollar annual fee for app hosting (specifically, opening a developer account). To address this, I will host the source code here on GitHub. If anyone volunteers to host it, I would be more than happy.

Nevertheless, there are a few alternative ways to deploy the app. One option is to open the app's source code on Xcode and manually deploy it to your devices. Alternatively, you can install the app's IPA archive using third-party tools, although I personally haven't tested any of them.

**Comment by sepsol** [comment]
@yuroyami Thanks for providing detailed information! Let me know when you feel like your iOS app is ready and I might be able to help with hosting it on Apple Store.

**Comment by yuroyami** [comment]
@sepsol, Delightful :) Stay tuned

**Comment by VivekHalakatti** [comment]
Any further updates on iOS syncplay😄?

**Comment by Et0h** [comment]
> Any further updates on iOS syncplay😄?

There is an unofficial project which provides Syncplay on iOS: https://github.com/yuroyami/syncplay-mobile/

It is listed at https://github.com/Syncplay/syncplay/discussions/574
